### ISSUE TITLE
import channelselector ModuleNotFoundError: No module named 'channelselector'

### ISSUE THREAD

**Issue by NoName211111** [kodiondemand/addon#234]
& python c:/Users/MY_PC/Desktop/animesaturn.py
Traceback (most recent call last):
  File "c:/Users/MY_PC/Desktop/animesaturn.py", line 10, in <module>
    import channelselector
ModuleNotFoundError: No module named 'channelselector'

**Comment by mac12m99** [comment]
Rifai seguendo quanto qui riportato, così è completamente inutile.
https://github.com/kodiondemand/addon/blob/master/CONTRIBUTING.md#segnalare-i-cambiamenti-di-struttura
