### ISSUE TITLE
Animeunity categorie vuote

### ISSUE THREAD

**Issue by NoName211111** [kodiondemand/addon#235]
![Screenshot_20200911_170508_org xbmc kodi](https://user-images.githubusercontent.com/60112822/92948766-331d1780-f45a-11ea-92a3-fb39968f5a01.jpg)

>
[kodi.log.txt](https://github.com/kodiondemand/addon/files/5210389/kodi.log.txt)
Non riesco vedere le categorie di animeunity sono vuote

**Comment by mac12m99** [comment]
Risolto con b16677e521487e134cd39ef727745117d59f48c9
Grazie della segnalazione!
