### ISSUE TITLE
Hdmario errore su seriehd

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#308]
[kodi.log](https://github.com/kodiondemand/addon/files/6573171/kodi.log)
HdMario2k e 4k sul canale serieHD.e-mail non funzionano su kod, invece dal browser funziona, su kod dice errore inaspettato, allego file.log, Grazie

**Comment by mac12m99** [comment]
HDmario risulta ora inaccessibile su quasi tutti i film, al suo posto c'è questo link:
https://t.me/s/ilcontrolloreoriginale/4

Chiudo quindi l'issue
