### ISSUE TITLE
Aniplay

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#318]
[kodi.log](https://github.com/kodiondemand/addon/files/6751310/kodi.log)

Aniplay problema con alcuni capitoli di one piece su Kod, andando sul canale aniplay/one piece (sub ita) se si cerca di aprire la Saga di Wano o la Saga di Zhou si riscontra un errore, alcuni capitoli li apre altri no, solo ed esclusivamente tramite Kod, non ho provato ad aggiungerlo in videoteca.

**Comment by Alhaziel01** [comment]
Prova sulla Beta, dovrebbe essere risolto

**Comment by Yoshinizar** [comment]
Ora provo

**Comment by Yoshinizar** [comment]
> Prova sulla Beta, dovrebbe essere risolto

Funziona perfetto anche questo  👍
