### ISSUE TITLE
Aniplay

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#319]
Se provo ad aggiungere alla videoteca Bleach (sub ita) trovo solo 20 puntate riconosce solo la prima saga (visto che il sito suddivide in capitoli, scansionato sia con tmdb show che tmdb, se provo ad aggiungerli saga per saga, non compare nulla, se provo a rinumerare le saghe o bleach intero mi da errore, questo lo fa con tanti anime di questo canale, se ci fosse la possibilità di rinumerare anche i capitoli, come ad esempio slam dunk sul canale è suddiviso stagione (1) 1-50/ stagione (2) 51-101, ed in teoria è sbagliata la rinumerazione di aniplay, perché è tutto una stagione, se potessi rinumerare 51/101 come seguito della prima stagione sarebbe ottimo
[kodi.log](https://github.com/kodiondemand/addon/files/6751354/kodi.log)

**Comment by Alhaziel01** [comment]
Prova sulla Beta, dovrebbe essere risolto

**Comment by Yoshinizar** [comment]
> Prova sulla Beta, dovrebbe essere risolto

Adesso funziona perfetto, Grazieeeeee
