### ISSUE TITLE
Aniplay non scansiona i nuovi episodi

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#330]
[kodi(1).log](https://github.com/kodiondemand/addon/files/6911737/kodi.1.log)
[kodi.log](https://github.com/kodiondemand/addon/files/6911738/kodi.log)
[My Hero Academia.zip](https://github.com/kodiondemand/addon/files/6911739/My.Hero.Academia.zip)
[One piece All'arrembaggio.zip](https://github.com/kodiondemand/addon/files/6911740/One.piece.All.arrembaggio.zip)

Aniplay non scansiona nuovi episodi, allego i due file kodi.log ognuna fatte dopo aver scansionato i nuovi episodi, e le due cartelle con le puntate
One piece 981 ma dovrebbero essere 985
My hero academia Fino alla stagione 5 con 17 episodi, ma dovrebbero essere 18.

Grazie

**Comment by Yoshinizar** [comment]
Problema Canale

**Comment by Alhaziel01** [comment]
È Stato Mandato un Fix, purtroppo bisogna aggiungere nuovamente le serie in videoteca perché possa funzionare

**Comment by Yoshinizar** [comment]
Va bene, ma devo cancellarli o posso sovrascriverli? Grazie

**Comment by Yoshinizar** [comment]
Va bene grazie come sempre 😎
