### ISSUE TITLE
Animesaturn non funziona 

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#334]
Animesaturn non funziona più, ma dal browser si
[kodi.log](https://github.com/kodiondemand/addon/files/6990718/kodi.log)

**Comment by mac12m99** [comment]
Ciao, potrebbe essere dovuto ad un problema momentaneo, per favore riprova ora

**Comment by mac12m99** [comment]
Ciao,
per favore prova ad installare la beta, dovrebbe essere risolto. Fammi sapere
PS
Se ritorni sulla stabile prima che il fix venga inviato anche li, potresti avere qualche problema

**Comment by Yoshinizar** [comment]
Ciao si nella beta adesso sembra funzionare
