### ISSUE TITLE
My hero academia non trova nuovi episodi (Aniplay)

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#335]
La scansione su aniplay funziona bene con altri cartoni e non ho problemi, ma con la serie My hero Academia, no, la scansione non trova i nuovi episodi 18 e 19, si ferma alla 17, in allegato cartella anime
[My Hero Academia [tt5626028].zip](https://github.com/kodiondemand/addon/files/6991759/My.Hero.Academia.tt5626028.zip)

GRAZIE

**Comment by mac12m99** [comment]
@Alhaziel01 Credo che in questo caso ci siano problemi con il renumber, aniplay divide le stagioni in più "serie" e il renumber confonde le stagioni (mette su tutte la 4°)

**Comment by Yoshinizar** [comment]
Non c'è soluzione per questo problema?

**Comment by Alhaziel01** [comment]
Il problema è che hai aggiunto come ultima stagione la 4 invece della 5, la gestione attuale della videoteca mantiene un solo link per canale (l'ultimo).

Siamo al lavoro per una riscrittura completa della videoteca, ma questo richiederà molto tempo.

Quello che puoi fare attualmente è aggiungere nuovamente l'ultima stagione...

**Comment by Yoshinizar** [comment]
Ciao, no io ho aggiunto la quinta stagione, solo che kodi la riconosce come 4 stagione quindi ho dovuto rinumerarla come quinta prima di aggiungerla,... Ho già raggiunto la serie die o tre volte oer aggiornsre gli episodi della quinta stagione, ma non si aggiorna

**Comment by Alhaziel01** [comment]
@Yoshinizar dal file tvshow.info risulta il link alla 4...

**Comment by Alhaziel01** [comment]
@Yoshinizar dal file tvshow.info risulta il link alla 4...

**Comment by Yoshinizar** [comment]
@Alhaziel01 Se vai su aniplay e vai sulla quinta stagione di questo cartone e lo apri, anziché darti 5x1 ecc ti da in alcuni episodi 4x1 ed è un errore, perché sono tutti 5 stagione, adesso ti mando una cartella con solo la quinta stagione e i screen

**Comment by Yoshinizar** [comment]
![Screenshot_2021-09-20-18-58-35](https://user-images.githubusercontent.com/72281082/134043400-efa4f0e7-08df-4f98-a4d0-296f0db6aacb.png)
![Screenshot_2021-09-20-18-58-46](https://user-images.githubusercontent.com/72281082/134043430-814bbdb6-7699-4ea5-9e36-4b1e7b575f12.png)
 Vedi è aniplay o io renumber di kod ad avere questo problema

**Comment by Yoshinizar** [comment]
Quindi mi tocca rinunerarlo prima di aggiungerlo alla videoteca

**Comment by Yoshinizar** [comment]
@Alhaziel01 ho cancellato tutte le stagione, anche l'intera cartella manualmente, ho aggiunto alla videoteca solo la stagione 5, poi ho cancellato un episodio ho riavviato kodi e non scansiona l'episodio cancellato facendo cerca nuovi episodi, metodo che con altri cartoni e serie funziona

**Comment by Alhaziel01** [comment]
Ho provato ad aggiungere My hero academia 5 da Aniplay e cancellato qualche episodio, alla scansione li riaggiunge senza problemi... (numerandola come 5x...)

mi gireresti il file aniplay_data.json in addon_data/plugin.video.kod/settings_channel?

**Comment by Yoshinizar** [comment]
Le prime 4 stagioni li ho da altri canali, la quinta stagione l'ho aggiunta per ultima da aniplay, prima ha sempre funzionato fino alla puntata 17, dopodiché ho dovuto aggiungerlo manualmente ad ogni puntata, l'ho zippato il file perché non lo caricava qui
[aniplay_data.zip](https://github.com/kodiondemand/addon/files/7208592/aniplay_data.zip)

**Comment by Alhaziel01** [comment]
Ok, ho capito (spero) dove si trova il problema...
Prova sulla beta a aggiungere nuovamente la stagione in videoteca

**Comment by Yoshinizar** [comment]
@Alhaziel01 Quando metti questo fix nella stabile me lo scrivi qua? O su telegram, grazie
