### ISSUE TITLE
Ho aggiornato Kodi alla versione 19 e in Kodi OnDemand on mi trova più niente

### ISSUE THREAD

**Issue by Speck95** [kodiondemand/addon#343]
Ho aggiornato ieri Kodi alla versione 19.0 e appena apro Kodi On Demand ed effettuo una ricerca non mi trova più nessun risultato. Non capisco se c'è correlazione tra l'aggiornamento e questo problema. Vi prego di aiutarmi a risolvere questo problema.

**Comment by Alhaziel01** [comment]
Hai aggiornato Kodi o hai fatto una installazione pulita?

Se hai aggiornato, ti consiglio di procedere con un'installazione pulita, il passaggio da 18 a 19 spesso causa problemi.

**Comment by Speck95** [comment]
Grazie mille per l'aiuto. Adesso provo a fare di nuovo l'istallazione. Ho installato un file manager per eliminare tutti i dati di Kodi altrimenti non credo che funziona se lo reinstallo e basta
