### ISSUE TITLE
Canale Mediaset - TG5

### ISSUE THREAD

**Issue by Gythion** [kodiondemand/addon#344]
Con l'ultimo aggiornamento - 1.7.1 - se vado a pescare TG5 con le sue sottosezioni, se vado su Servizi, non sono più aggiornati, ci sono titoli di anni fà. Fino alla versione 1.7, funzionava perfettamente.

**Comment by mac12m99** [comment]
E' una questione di ordinamento, ora le serietv vengono ordinate per data crescente (così mostra prima il primo episodio) e i programmi tv per data decrescente (episodio/servizio più recente per primo).
Grazie delle segnalazione.
