### ISSUE TITLE
Animesaturn - Server Primario e Secodario

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#346]
Salve di solito su Animesaturn tramite kod i server primario e secondario non funzionano mai, gentilmente è possibile sistemare questi due server, ad esempio Inuyasha come tutti gli altri, i server. Primario e secondario funziinano sempre, invece su kod danno errore, ma aprendoli tramite browser funziinano.
![Screenshot_2021-09-29-07-21-09](https://user-images.githubusercontent.com/72281082/135208388-d1c1ae36-c693-4135-adf5-2a930de25d72.png)
![Screenshot_2021-09-29-07-21-01](https://user-images.githubusercontent.com/72281082/135208402-81586b4d-79cd-44b2-9b95-58b03061a635.png)

Grazie

**Comment by Alhaziel01** [comment]
Fixato
