### ISSUE TITLE
Impostazioni

### ISSUE THREAD

**Issue by Gythion** [kodiondemand/addon#347]
Perchè mi appare l'icona di aggiornamento (la nuvola con una freccia in giù) accanto ad "Impostazioni"?

**Comment by mac12m99** [comment]
Manda uno screen per favore

**Comment by xXTimmy89Xx** [comment]
> Manda uno screen per favore

Il bug in questione è stato fixato con il commit 1895883 però effettivamente abilitando la vista touch è ancora presente l'icona menzionata da @Gythion 

![screenshot00000](https://user-images.githubusercontent.com/53865707/135784795-e810f6cf-f131-44a2-b12e-eb08b582b8ec.png)

![screenshot00000](https://user-images.githubusercontent.com/53865707/135816894-af27e566-3f5c-41e3-a521-4f716bfc4187.png)

**Comment by Alhaziel01** [comment]
quell'icona non è un bug

**Comment by xXTimmy89Xx** [comment]
> quell'icona non è un bug

Solo a scopo informativo quale sarebbe la sua utilità/funzione ?
