### ISSUE TITLE
Segnalazione piccoli bug nella sezione Adesso in onda e richiesta inserimento canali +24

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#348]
Se un titolo nella sezione Adesso in onda contiene un carattere speciale come i due punti, & o altri su superguidatv.it su KoD viene visualizzato incompleto, per esempio il film Code Name: Geronimo  e Boog & Elliot 4 - Il mistero della foresta

![Cattura](https://user-images.githubusercontent.com/53865707/135691302-cd9293ea-1d54-40e5-9ac8-40e9d743adcc.JPG)

![screenshot00000](https://user-images.githubusercontent.com/53865707/135691317-1ea0eab4-8a64-43a1-a6b4-7deb863487aa.png)

![Cattura2](https://user-images.githubusercontent.com/53865707/135692809-d6238adc-49b4-4164-ba4b-79104348703d.JPG)

![screenshot00000](https://user-images.githubusercontent.com/53865707/135692820-d97424a2-8b6b-4923-a9dc-e8fca72886eb.png)

di conseguenza essendo il titolo incompleto le informazioni di The Movie Database sono errate.

Il secondo bug invece è che al posto di visualizzarsi il canale in cui viene trasmesso il film viene visualizzata la dicitura Versione consigliata solo a un pubblico adulto o Visto censura su alcuni canali 

![screenshot00001](https://user-images.githubusercontent.com/53865707/135692130-9f4b7100-b43f-472c-82f0-f933d794d80e.png)

![screenshot00007](https://user-images.githubusercontent.com/53865707/135692134-68bb9d16-7db7-4e92-be01-2c8aa39f8026.png)

Mentre se fosse vorrei richiedere l'inserimento delle informazioni dei canali +24 

![image](https://user-images.githubusercontent.com/53865707/135692401-ca44b66a-c8ac-4ea1-9db4-09746c90942d.png)

![image](https://user-images.githubusercontent.com/53865707/135692414-bb9698f6-a838-4bcf-a230-0a27c223c099.png)

![image](https://user-images.githubusercontent.com/53865707/135692551-5014d7f5-0fbe-4a02-9dfe-ddeb7fb2c024.png)

Come sempre grazie anticipatamente.

![screenshot00003](https://user-images.githubusercontent.com/53865707/135693172-9a656e63-ddfd-40f9-ac32-c707e08494b8.png)

![screenshot00000](https://user-images.githubusercontent.com/53865707/135693177-8c32fd5e-2b2d-4856-8980-c84b27f5018a.png)

Ultimissima cosa ho rinominato le sezioni in un modo corretto e più intuitivo basandomi su quelli originali di superguidatv.it e mi chiedo se non fosse il caso di mettere di default, penso sia molto più intuitivo così.

{
    "settings": {
        "film1": "[Film in TV] Nazionali Dtt", 
        "film2": "[Film in TV] Mediaset Premium", 
        "film3": "[Film in TV] Sky Intrattenimento", 
        "film4": "[Film in TV] Sky Cinema", 
        "film5": "[Film in TV] Sky Primafila", 
        "now1": "[Ora in onda] Nazionali Dtt", 
        "now2": "[Ora in onda] Mediaset Premium", 
        "now3": "[Ora in onda] Sky Intrattenimento", 
        "now4": "[Ora in onda] Sky Doc E Lifestyle", 
        "now5": "[Ora in onda] Sky Cinema"
    }
}

Se qualcuno lo volesse basta andare nel percorso kodi\userdata\addon_data\plugin.video.kod\settings_channels\filmontv_data.json e sostituire il contenuto.

**Comment by mac12m99** [comment]
Ciao,
i bug da te segnalati dovrebbero ora essere risolti, fammi sapere.
Per quanto riguarda i canali +24, non trovo la sezione sul sito, dove si trova? O ti riferisci al pulsante domani?

Per il nome delle sezioni.. era una precisa scelta quella di non indicare la fonte di default.

**Comment by xXTimmy89Xx** [comment]
> Ciao, i bug da te segnalati dovrebbero ora essere risolti, fammi sapere. Per quanto riguarda i canali +24, non trovo la sezione sul sito, dove si trova? O ti riferisci al pulsante domani?
> 
> Per il nome delle sezioni.. era una precisa scelta quella di non indicare la fonte di default.

Prima di tutto grazie del fix, i canali +24 fanno parte della sezione https://www.superguidatv.it/film-in-tv/oggi/sky-cinema ma vedo che ora sono presenti

**Comment by mac12m99** [comment]
Perfetto, allora chiudo.
Grazie della segnalazione.
