### ISSUE TITLE
Cerca serie tv su Altadefinizionecommunity non trova la serie Squid Game

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#350]
Su altadefinizionecommunity quando si prova a cercare la serie Squid Game nella sezione cerca serie tv non viene trovato nessun risultato 

![photo_2021-10-03_19-59-04 (2)](https://user-images.githubusercontent.com/53865707/135778141-3c7ca966-1809-4ecf-911f-e798e262f626.jpg)

La serie in questione però appare nella sezione serie tv anche se non viene visualizzato parte della dicitura [Sub ITA]

![photo_2021-10-03_19-59-04](https://user-images.githubusercontent.com/53865707/135778165-0cdd4435-8d2b-4b88-a1f0-cb2f3c6e5e6a.jpg)

la ricerca da sito la trova senza problemi

![Cattura2](https://user-images.githubusercontent.com/53865707/135778384-b72092c4-ea51-49b0-9301-a7b582e9d926.JPG)

Il problema in questione si era presentato anche con un altra serie della quale purtroppo non ricordo il nome,

**Comment by mac12m99** [comment]
Ora non dovrebbe più dare questo problema, confermi?
Sulla stabile c'è ancora "Sub-" ma sulla beta è risolto anche questo, lo manderò insieme ad altri essendo una piccolezza.

**Comment by xXTimmy89Xx** [comment]
> Ora non dovrebbe più dare questo problema, confermi? Sulla stabile c'è ancora "Sub-" ma sulla beta è risolto anche questo, lo manderò insieme ad altri essendo una piccolezza.

Si confermo confermo il corretto funzionamento e avevo notato anche il fix del sub-ita sulla beta, grazie come sempre.
