### ISSUE TITLE
Problema risultati ricerca globale per genere serie tv e film

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#352]
La seconda pagina di risultati della ricerca globale per genere sia della sezione serie tv che della sezione film restituisce nessun elemento da visualizzare

![screenshot00001](https://user-images.githubusercontent.com/53865707/135819278-4b63cbdc-448c-49c3-80f0-c372d5133913.png)

**Comment by Alhaziel01** [comment]
Potresti provare sulla beta e dirmi se riscontri lo stesso problema?

**Comment by xXTimmy89Xx** [comment]
> Potresti provare sulla beta e dirmi se riscontri lo stesso problema?

Confermo che il problema è stato risolto, grazie come sempre.
