### ISSUE TITLE
Kod esce dalla videoteca dopo aver concluso un episodio

### ISSUE THREAD

**Issue by PuffoCyano** [kodiondemand/addon#353]
Ciao, da qualche giorno sto notando che quando finisco di guardare un episodio di una serie TV su KoD, quest'ultimo mi porta completamente fuori dalla videoteca invece di riportarmi alla lista degli episodi; di solito quando terminavo un episodio, KoD mi mostrava subito la lista degli episodi di quella serie TV; forse con gli ultimi aggiornamenti questo non accade più.

Condivido il link del log generato: https://anonfiles.com/Peqd66Ldub

Grazie mille per il support :smile:

**Comment by Alhaziel01** [comment]
Potresti provare la beta e dirmi se riscontri lo stesso problema?

**Comment by PuffoCyano** [comment]
Dove la posso trovare la beta? Nelle releases non la vedo

**Comment by PuffoCyano** [comment]
Anche con la versione Beta (quella che punta al branch master) accade la stessa cosa; inoltre aggiungerei che in alcuni casi, quando finisce l'episodio, si freeza e mi tocca riavviare Kodi.
Aggiungo che ho anche testato la versione Alpha ma il problema persiste; inoltre ho notato che quando ho installato la beta, per un momento, quando è terminato l'episodio, è ritornato alla lista degli episodi per 1/2 secondi ma era ancora in corso il caricamento, e una volta terminato il caricamento è uscito completamente dalla videoteca. Quindi sembrerebbe come se cercasse di fare qualcosa alla fine ma non riuscendo, fallisce qualcosa ed esce completamente; inizialmente pensavo potesse avere a che fare con l'opzione "Vai all'episodio successivo automaticamente", ma anche disabilitandola non ho risolto il problema.
Concludo dicendo che sto usando Kodi 19.1, ma il problema l'ho riscontrato già con la versione 18.9 qualche giorno fa.

Spero di aver dato sufficienti info e che si possa risolvere al più presto, perchè l'addon è ottimo :sunglasses:

**Comment by Alhaziel01** [comment]
potresti inviare un log?

**Comment by PuffoCyano** [comment]
[log_kod.txt](https://github.com/kodiondemand/addon/files/7296706/log_kod.txt)
Certo; ti lascio questo pezzo di log; è quello che vedo dopo aver selezionato un episodio, arrivato alla fine e chiuso la puntata; a questo punto KoD esce completamente dalla videoteca.

**Comment by PuffoCyano** [comment]
Ciao; volevo aggiornarti che il problema non si sta verificando più; forse con l'ultimo aggiornamento è stato risolto

**Comment by mac12m99** [comment]
Ottimo, chiudo allora.
Grazie della segnalazione.
