### ISSUE TITLE
maxstream è deceduto in kod ma worka da browser

### ISSUE THREAD

**Issue by omgfrost** [kodiondemand/addon#354]
Provato di tutto stasera 2 cell e 1 pc
![Screenshot_20211006-233411541](https://user-images.githubusercontent.com/14861120/136287359-7e0887a0-2ba4-4d47-be51-3c33c956c5b9.jpg)
![Screenshot_20211006-232048742](https://user-images.githubusercontent.com/14861120/136287364-4c641638-4d13-434f-a5fe-88317fcbcd31.jpg)
![Screenshot_20211006-231849558](https://user-images.githubusercontent.com/14861120/136287369-395ec633-0356-4ba5-8d17-07a524f6f099.jpg)
L'ultima screen è dalla beta...
Credevo di impazzire :X

**Comment by omgfrost** [comment]
Ok, ho preso il log da pc rifacendo la procedura per maxstream:
Log:https://anonfiles.com/5691i2M9u4

**Comment by mac12m99** [comment]
Fixato, grazie della segnalazione.

**Comment by omgfrost** [comment]
> Fixato, grazie della segnalazione.

Glad to help!
