### ISSUE TITLE
ilcorsaronero piccolo bug ed eventuali migliorie 

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#356]
Su ilcorsaronero prendendo come esempio la sezione BDRiP possiamo notare che i titoli dei film o del file in alcuni casi sono incompleti e di conseguenza è impossibile determinare di che film si tratti (esempio il film dei me contro te o come esempio Pack 31 che non è il titolo di un film ma un pacchetto contente 5 film), in più non è possibile determinare la qualità del film visto che nativamente sul sito spesso e volentieri viene inserita nel nome completo del file (esempio il primo film The.Untouchables.Gli.Intoccabili.1987.iTA.ENG.AC3.SUB.iTA.ENG.BluRay.1080p.x264.jeddak-MIRCrew - su KoD viene visto semplicemente come The Untouchables Gli intoccabili ed è impossibile determinarne la qualità) e se per come è strutturato ora il canale dovrebbe estrapolare la qualità considerando che nel secondo film Agora è presente, sembra non funzionare correttamente o per lo meno quando vuole, credo che la cosa migliore sia eventualmente il mantenimento del nome originale del file ma sono certo che troverete voi la soluzione più corretta come sempre.

Grazie anticipatamente.

![screenshot00000](https://user-images.githubusercontent.com/53865707/137583170-538f2f2f-b3aa-4fb7-8162-9728e9a24059.png)

![Immagine 2021-10-16 115013](https://user-images.githubusercontent.com/53865707/137583183-5ff8f8ef-a655-4749-86ce-6912789a1139.jpg)

**Comment by mac12m99** [comment]
Ciao,
sulla beta ho appena mandato una possibile miglioria: invece che usare il titolo (che non viene mostrato in toto), utilizzo l'ultima parte dell'URL, la libreria che usiamo per estrarre le info sembra in grado di gestirlo lo stesso eliminando i caratteri _.
Per quanto riguarda i casi dei "pacchetti" purtroppo gestirli non credo valga la pena (troppo complesso per troppo pochi torrent).

Mantenere il nome originale romperebbe lo "standard grafico" dell'addon, e tanto sono sicuro che molti non sanno leggere i tag...

**Comment by xXTimmy89Xx** [comment]
> Ciao, sulla beta ho appena mandato una possibile miglioria: invece che usare il titolo (che non viene mostrato in toto), utilizzo l'ultima parte dell'URL, la libreria che usiamo per estrarre le info sembra in grado di gestirlo lo stesso eliminando i caratteri _. Per quanto riguarda i casi dei "pacchetti" purtroppo gestirli non credo valga la pena (troppo complesso per troppo pochi torrent).
> 
> Mantenere il nome originale romperebbe lo "standard grafico" dell'addon, e tanto sono sicuro che molti non sanno leggere i tag...

Buonasera, sto testando giusto ora le migliorie sulla beta, e devo dire che è decisamente meglio anche se in alcuni casi continua purtroppo a non riuscire a estrarre la qualità, per esempio L'ultimo Samurai o Blow ma è già un notevole miglioramento, grazie mille.

![screenshot00000](https://user-images.githubusercontent.com/53865707/138144703-9df73d5f-dfad-4276-b393-ffa0f53f6cf2.png)

![Immagine 2021-10-20 194605](https://user-images.githubusercontent.com/53865707/138144722-0b8a7fa0-3793-4b99-ae82-be1951dfb8cb.jpg)

**Comment by mac12m99** [comment]
Quei 2 erano a causa della mancanza della tipologia di RIP, ora rileva la risoluzione senza necessariamente il tipo di rip.
Ho già passato sulla stabile perché non credo causi problemi.

**Comment by xXTimmy89Xx** [comment]
> Quei 2 erano a causa della mancanza della tipologia di RIP, ora rileva la risoluzione senza necessariamente il tipo di rip. Ho già passato sulla stabile perché non credo causi problemi.

Ho appena effettuato ulteriori test sulla stabile e sembra funzionare tutto perfettamente, grazie mille rimane solo il bug dell'autoplay con il canale ora ma ogni cosa a suo tempo, penso si possa chiudere, ottimo lavoro come sempre.

**Comment by mac12m99** [comment]
Ottimo, chiudo.
Si il crash con l'autoplay è un po' complicato da debuggare..
