### ISSUE TITLE
Possibilità aggiunta server Streamlare canale cinemalibero

### ISSUE THREAD

**Issue by xXTimmy89Xx** [kodiondemand/addon#361]
Tra i server a disposizione nel canale cinemalibero sembra essere apparso un novo serve Streamlare valutate eventualmente la sua implementazione se possibile, si ringrazia l'utente @Rosen7012 per la segnalazione

**Comment by mac12m99** [comment]
Aggiunto con faa51a547716e1f6c5c36aa9acc5383d6f0f6c42
