### ISSUE TITLE
Caricamento stream lento su Android

### ISSUE THREAD

**Issue by PuffoCyano** [kodiondemand/addon#365]
Ciao, volevo segnalare un rallentamento durante l'apertura degli stream sulla versione Android di Kodi; in particolare la mia situazione è la seguente: ho una raspberrypi a cui è collegato un'hardisk che funge da memoria di rete contenente i vari file della libreria di Kodi; qui ho anche aggiunto una cartella che viene utilizzata da KoD in modo da avere Serie TV e Film sempre sincronizzati con i vari dispositivi; inoltre ho anche un db mysql sulla raspberry sempre per la sincronizzazione tra più dispositivi. Il tutto sembra funzionare bene, soprattutto sulla versione Windows che ho sul PC, infatti qui non noto nessun rallentamento ne con i miei file ne con gli stream di KoD; da questa versione Windows ho creato un immagine di backup e l'ho ripristinata sul mio smartphone e sulla smart TV, entrambi con Android. Anche in questo caso tutto apposto se non per il rallentamento dell'apertura degli stream di KoD, soprattutto con le serie TV con parecchi episodi; inizialmente pensavo fosse un problema di performance del dispositivo, ma quando ho notato che il problema si ripeteva anche sul mio OnePlus 9 ho capito che non era quello. 
Da precisare che i miei file caricati sull'hardisk esterno, vengono riprodotti immediatamente dalla videoteca di Kodi, sia su Windows che su Android; quindi il rallentamento si nota solo con gli stream di KoD, ovvero quando provo a selezionare un episodio dalla videoteca di Kodi per far comparire i vari canali.
Per questo penso che ci sia qualche problema su Android ma non sono ancora riuscito a capire per quale motivo.
Avete qualche suggerimento oppure ho sbagliato qualcosa?
Grazie mille :smile: 

P. S. Spero che si possa risolvere questo problemino perchè il vostro addon è il migliore per questo. Continuate cosi che state facendo un ottimo lavoro ;)

**Comment by PuffoCyano** [comment]
Ciao; volevo aggiornarvi che ho risolto il problema :smile: alla fine non è un problema dell'addon e neanche del DB in remoto, ma il tutto è legato ad un aspetto architetturale; infatti finora ho installato un server Samba (SMB) sulla raspberry in modo da rendere accessibile l'hardisk all'interno della rete LAN; questo ha sempre funzionato e continua a funzionare ma ho scoperto che Samba è ottimo per i sistemi Windows (ecco perchè il mio Kodi sul PC funziona perfettamente), mentre per i sistemi Unix (MacOs, Linux e di conseguenza Android) è meglio installare un server NFS sulla raspberry; infatti ora sulla mia raspberry ho sia un server SMB che uno NFS, il primo lo uso su Kodi sul mio PC, come prima, mentre sul mio smartphone e sulla mia smart TV uso il secondo, e con questo metodo ho risolto il problema e gli stream si aprono velocemente.
Pertanto posso chiudere l'issue, ma prima di farlo vorrei chiedere un'ultimo consiglio: per riprendere la visione dallo stesso punto tra i vari dispositivi come posso fare? Con il DB mysql funziona tutto ma solo con i miei file personali, mentre con gli stream di KoD no; quindi mi chiedevo se è possibile (se si, come) configurare il database remoto che vedo nelle impostazioni di KoD.

Grazie :smile:

**Comment by mac12m99** [comment]
Ciao,
sono contento tu sia risucito a risolvere, rispondo alla tua ultima domanda: allo stato attuale non è possibile "nativamente", ho un idea per poterlo fare ma non l'ho mai provata..

Tutti i dati dell'addon sono salvati in questo percorso
/.kodi/userdata/addon_data/plugin.video.kod/
Impostazioni, cache e anche il punto di visione (per la precisione db.sqlite, tabella viewed)
Se questo percorso fosse in realtà un percorso di rete, montato per sembrare locale, sia kodi che KoD a livello puramente teorico non dovrebbero battere ciglio.
Ciò porterebbe tuttavia a problemi qualora più dispositivi ci accedano in contemporanea, non so se dato il tuo utilizzo non accadrebbe mai..
