### ISSUE TITLE
Tasto OK non funzionante TV ANDROID

### ISSUE THREAD

**Issue by GCItaly** [kodiondemand/addon#367]
Buongiorno e complimenti per l'ottimo lavoro.

Vorrei segnalare che selezionando da un qualsiasi canale un filmato, premendo il tasto OK del telecomando, il prg tenta di aprirlo
ma inutilmente. L'unica possibilità è tenere premuto il tasto OK fino all'apertura del popup, che ha il comando RIPRODUCI.

**Comment by mac12m99** [comment]
Ciao,
sembrerebbe più qualcosa legato alla skin.. potrestri dare maggiori info su versione di kodi e skin?

**Comment by GCItaly** [comment]
Confluence e Kodi 19.3
    Il giovedì 16 dicembre 2021, 19:27:42 CET, mac12m99 ***@***.***> ha scritto:  
 
 


Ciao,
sembrerebbe più qualcosa legato alla skin.. potrestri dare maggiori info su versione di kodi e skin?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mac12m99** [comment]
Ho installato la confluence e testato e pare funzionare, potresti indicare di preciso la sezione oppure fare un video?
