### ISSUE TITLE
IlCorsaronero

### ISSUE THREAD

**Issue by Bike64** [kodiondemand/addon#370]
Kodiondemand non include nella ricerca dei film il sito "ILCORSARONERO" anche se risulta nella lista. Credo abbia cambiato estensione. Grazie

**Comment by mac12m99** [comment]
Ciao,
il sito corretto (ilcorsaronero.link) è attualmente offline da un po', altri siti sono quasi sicuramente cloni o fake.
Se ritornerà on lo rivedrai nella ricerca, sennò lo disabiliteremo proprio.
