### ISSUE TITLE
Dreamsub

### ISSUE THREAD

**Issue by Apolllo7** [kodiondemand/addon#371]
Tutti i contenuti del canale dreamsub non sono più visibili su kod. Un messaggio informa che dreamsub.stream non è più raggiungibile, ma il link esatto del canale è dreamsub.cc

**Comment by mac12m99** [comment]
Si è trattato di un problema momentaneo, adesso pare funzionare.
Comunque in effetti il bot che ci aggiorna i domini non ha funzionato, grazie della segnalazione, vedo di aggiustarlo.
