### ISSUE TITLE
Elementum per canali Torrent

### ISSUE THREAD

**Issue by morisgroves** [kodiondemand/addon#372]
Ciao!
ho notato che Elementum non funziona su dispositivi android 10 con installato Kodi 19.3, sembra un problema noto:
https://github.com/elgatito/plugin.video.elementum/issues/669
https://github.com/elgatito/plugin.video.elementum/issues/847

Sto provando a cercare un'alternativa ma per ora non ho trovato nulla, è un peccato perchè ad esempio il canale ilcorsaronero ha contenuti di ottima qualità.
Riscontrate lo stesso problema?
grazie!

**Comment by xXTimmy89Xx** [comment]
@morisgroves Hai già dato uno sguardo alla possibile soluzione disponibile nel canale telegram di supporto di KoD? in caso contrario ecco a te https://t.me/kodiondemand/191325

**Comment by morisgroves** [comment]
spiacente colpa mia ho Signal e non Telegram! sarebbe possibile postare il link all'apk anche qua? grazie mille!
sono riuscito a trovare solo questo https://www.youtube.com/watch?v=YTzjPrSQkEg

**Comment by xXTimmy89Xx** [comment]
Molti di voi saranno a conoscenza del problema di elementum e relativi permessi di Android 10 o superiore, questo problema può essere raggirato al momento in due modi 1️⃣ il primo è ricompilando Apk ufficiale di Kodi e modificando il Target SDK che attualmente è di Android 10 con quello di Android 9 (ovvero modificandolo da 29 a 28) che è lo stesso motivo per la quale su alcuni fork di Kodi come Nodi non viene riscontrato il problema, quindi per i più pigri o per i meno smanettoni o per chi non vuole fork ecco a voi Apk di Kodi 19.3 ricompilato per il corretto funzionamento di elementum su Android 10 o superiore per entrambe le architetture, usando questo metodo potrebbe essere necessaria un installazione pulita e nel caso non abbiate voglia sarà sufficiente andare nel percorso storage/Android/data/ rinominare la cartellate org.xbmc.kodi disinstallare apk attuale e ripristinare il suo nome originale una volta installato uno dei due apk in base alla vostra architettura per non perdere nulla, 2️⃣ il secondo invece e installare a parte l'apk ElementumService e una versione modifica dell'addon elementum mantenendo la versione originale di Kodi reperibili qui https://github.com/StefanIlchev/ElementumService/releases con questo modo dovrete star dietro manualmente ai vari aggiornamenti di ElementumService

[kodi-19.3-Matrix-armeabi-v7a_28_apk](https://anonfiles.com/x3R1gaB0xf/kodi-19.3-Matrix-armeabi-v7a_28_apk)

[kodi-19.3-Matrix-arm64-v8a_28_apk](https://anonfiles.com/n0R2gcBfx5/kodi-19.3-Matrix-arm64-v8a_28_apk)

**Comment by morisgroves** [comment]
grandissimo grazie!

**Comment by morisgroves** [comment]
Ciao!
Riapro la discussione perchè ricompilando Kodi 21 per modificare il Target SDK ho notato che non punta più alla 29, o meglio non punta più a nessuna versione.
Si può quindi installare la versione da Google Play senza dover più ricompilare nulla?
Grazie!

**Comment by xXTimmy89Xx** [comment]
Ciao @morisgroves, Il problema dei permessi di Elementum che si presentava con versione di Android pari o superiore alla 10 dovrebbe essere stato risolto con le ultime versioni di quest'ultimo sulla maggior parte delle rom, pertanto dovresti poter tranquillamente usare la versione ufficiale di Kodi reperibile direttamente sul sito ufficiale.

**Comment by morisgroves** [comment]
perfetto grazie!
