### ISSUE TITLE
Informazioni

### ISSUE THREAD

**Issue by Enzoinventor** [kodiondemand/addon#374]
Salve,
Apprezzo moltissimo il vostro lavoro e ho letto tutta la vostra wiki.
Sto cercando di prendere confidenza con il codice.
Ho fatto il fork di questo progetto per fare delle prove in locale ma mi sfugge qualcosa.
Se volessi aggiornare l'app dal mio fork, quali file esattamente andrebbero modificati per far puntare l'aggiornamento dal mio fork?
Inoltre dopo il fork ho abilitato le azioni ma mi da sempre errore token.
Quali sono i fork necessari per fare funzionare correttamente tutto il programma?
Ringrazio anticipatamente.

**Comment by mac12m99** [comment]
Salve,
se intendi fare in modo che l'addon installato su un dispositivo "non di sviluppo", sia legato al tuo repo, devi modificare questa riga:
https://github.com/Enzoinventor/addon/blob/master/platformcode/updater.py#L26
le variabili branch, user e repo rappresentano il repo e il ramo a cui l'updater punta, volendo puoi fare anche il tuo installer con una modifica simile (in aggiunta a quella nel repo 'addon'):
https://github.com/kodiondemand/utilities/blob/master/KoD-installer/downloader_service.py#L21

Se invece intendi solo fare prove in locale, quelle variabili sono ininfluenti, dovresti però scaricare la tua repo con git in modo da disattivare l'updater e attivare le funzionalità di debug:
https://github.com/kodiondemand/addon/wiki/dev-mode

Per quanto riguarda le azioni si tratta praticamente solo dell'aggiornamento dei domini, che fallisce perchè una volta eseguito deve pubblicare sul repo i domini aggiornati, e per farlo deve avere accesso in scrittura, pertanto dovrebbe bastare creare un token chiamato API_TOKEN_GITHUB coi permessi giusti
https://github.com/kodiondemand/addon/blob/master/.github/workflows/updateDomains.yml#L30
Comunque, a meno che tu non voglia giocarci un po', attivarlo è inutile, puoi sempre scaricare gli ultimi commit da qui e tenere aggiornato il tuo fork.

Grazie dell'interesse :)
Se facessi qualche modifica di interesse comune (fix o implentazione di nuove funzioni), manda una pull request!
Per altre domande chiedi pure, tempo permettendo rispondiamo.

**Comment by Enzoinventor** [comment]
Salve,
Grazie per le tempestive risposte.
Quindi se ho capito bene, l'aggiornamento che fate è solo per i canali.
Se un'utente volesse aggiungere delle funzioni al menù con delle icone, bisognerebbe ricompilare anche lo zip dell'addon ?
Inoltre ho notato che la vostra cartella contenente il file zip si trova su un'altro repository dove avete il sito con tutte le informazioni e il download. Quindi per far funzionare il tutto bisogna avere il fork di questi 3 repository ? 
E tornando al discorso delle prove per fare dei test puntando al mio fork, basterà modificare soltanto il file xml contenuto nello zip?
Grazie ancora.

**Comment by Enzoinventor** [comment]
Ho in mente di aggiungere dei comandi vocali per sfogliare tutti i menù e fare le ricerche.
Oltre ad aggiungere qualche canale in futuro.

**Comment by mac12m99** [comment]
> Salve, Grazie per le tempestive risposte. Quindi se ho capito bene, l'aggiornamento che fate è solo per i canali. 

"Update channel domains"? Si, segue i redirect e aggiorna l'url contenuto in channel.json

> Se un'utente volesse aggiungere delle funzioni al menù con delle icone, bisognerebbe ricompilare anche lo zip dell'addon ? 

No, puoi benissimo scaricare il repo con git dentro .kodi/addons e da kodi abilitare l'addon, poi puoi lavorare col tuo editor preferito direttamente dentro la cartella .kodi, avendo quindi tutte le modifiche direttamente testabili da kodi (non serve nemmeno riavviarlo).
Noi per svilupparlo facciamo in questo modo.
 
> Inoltre ho notato che la vostra cartella contenente il file zip si trova su un'altro repository dove avete il sito con tutte le informazioni e il download. Quindi per far funzionare il tutto bisogna avere il fork di questi 3 repository ? 

Definisci "far funzionare il tutto"

> E tornando al discorso delle prove per fare dei test puntando al mio fork, basterà modificare soltanto il file xml contenuto nello zip? Grazie ancora.

Per fare dei test su altri dispositivi che non siano quello da cui sviluppi, basta modificare updater.py come descritto prima, andrà ovviamente a sovrascrivere la versione ufficiale (farne coesistere 2 diverse al momento non è possibile)

> Ho in mente di aggiungere dei comandi vocali per sfogliare tutti i menù e fare le ricerche.
Oltre ad aggiungere qualche canale in futuro.

Per i comandi vocali dubito fortemente potrai farlo modificando l'addon, ti servirà un programma esterno che riconosce i comandi e li manda a kodi tramite https://kodi.wiki/view/JSON-RPC_API
Su questo possiamo aiutarti solo per passare i giusti parametri:
https://kodi.wiki/view/JSON-RPC_API/v12#Addons.ExecuteAddon

**Comment by Enzoinventor** [comment]
> Definisci "far funzionare il tutto"
Dal momento che aggiungo la sorgente  https://kodiondemand.github.io/repo/ sul mio kodi,
vedo poi il file zip di installazione dell'addon.
Quello che non mi è chiaro è quanto segue: facendo il fork del progetto e volendo fare degli aggiornamenti di test o ricompilarla da 0, dovrei modificare la url della sorgente su kodi in modo che punti sul mio fork, ma nel fork non è presente lo zip installer di kodiondemand perchè si trova su un'altro repository.
Quindi quello che mi chiedevo è: dovrei fare il fork del repository dove risiede l'installer? 
all'interno dell'installer ci sarà da modificare anche li la url di puntamento al fork?
Grazie per la pazienza.

**Comment by mac12m99** [comment]
Puoi farlo e funzionerebbe, tuttavia non serve tutto sto giro, puoi semplicemente modificare il file updater.py prima dal tuo repo e poi  direttamente nel dispositivo e riavviare, dovrebbe sovrascriversi con la versione presente sul tuo repo.
Se invece intendi exnovo, oltre ovviamente a modificare updater.py sul tuo repo, dovresti modificare lo zip dell'installer e farglielo installare, anche localmente.

**Comment by Enzoinventor** [comment]
Grazie mille per le spiegazioni, ero convinto che era necessario avere quel file zip per poter cominciare.
Ero convinto di questo perchè fino ad adesso ho sempre installato su kodi programmi tramite il file zip e mai da un repository.
Quindi nel mio caso, sono andato su aggiungi sorgente, inserisco https://github.com/Enzoinventor/addon ma non mi mostra alcun file.

**Comment by mac12m99** [comment]
Per fare così dovresti fare il tuo sito github.io, secondo me fai prima a modificare l'installer e installarlo a mano (come tral'altro hai detto di essere abituato).
Basta modificare lo zip, non serve clonare il repo

Comunque secondo me ti conviene iniziare prima da kodi su pc come ti ho descritto, poi quando ti servirà testare su tv installi dal tuo repo.

**Comment by Enzoinventor** [comment]
ok grazie mille,
scarico lo zip e modifico il nome utente .
Per adesso grazie per le dritte.

**Comment by Enzoinventor** [comment]
Ciao ho finalmente capito il mio problema:
ho sempre aggiunto file zip su kodi da url e mai direttamente e questo mi aveva un po' confuso.
Soltanto adesso ho capito che dopo le modifiche che mi hai detto di fare, bastava scaricare il file rar dal mio github e importarlo direttamente su kodi tramite una penna usb.
Ho provato a creare un file vuoto sul mio github e cliccando su aggiorna applicazione, ha funzionato mostrandomi anche il numero del commit.
Grazie ancora per le dritte.
