### ISSUE TITLE
Download su USB non funziona su dispositivi android

### ISSUE THREAD

**Issue by aandroide** [kodiondemand/addon#378]
Salve,
sto usando Kodi on Demamd su mibox android ed ho provato ad abilitare il download in impostazioni.
Volevo spostare il percorso dei download direttamente sulla penna USB che è collegata a mibox ma mi viene mostrato un'errore: assicurati che la cartella selezionata sia scrivibile e che il nuovo nome della cartella sia valido.
Ovviamente la penna USB collegata a un PC funziona benissimo.
Ho provato a installare Kodi su PC e fa' selezionare qualsiasi fonte per il download senza problemi.
Sembrerebbe che manchino i permessi di scrittura solo sui dispositivi Android.
Ho anche provato a collegare la penna USB con un cavo otg sul cellulare e anche qui mi viene mostrato lo stesso errore.

Grazie in anticipo.

**Comment by aandroide** [comment]
Risolto, su Kodi la penna USB deve essere formattata in exfat. NTFS non va bene e nemmeno fat32 in quanto non è in grado di gestire file singoli superiori ai 4 GB.

**Comment by xXTimmy89Xx** [comment]
> Salve, sto usando Kodi on Demamd su mibox android ed ho provato ad abilitare il download in impostazioni. Volevo spostare il percorso dei download direttamente sulla penna USB che è collegata a mibox ma mi viene mostrato un'errore: assicurati che la cartella selezionata sia scrivibile e che il nuovo nome della cartella sia valido. Ovviamente la penna USB collegata a un PC funziona benissimo. Ho provato a installare Kodi su PC e fa' selezionare qualsiasi fonte per il download senza problemi. Sembrerebbe che manchino i permessi di scrittura solo sui dispositivi Android. Ho anche provato a collegare la penna USB con un cavo otg sul cellulare e anche qui mi viene mostrato lo stesso errore.
> 
> Grazie in anticipo.

Purtroppo [è un problema noto](https://community.sony.it/t5/android-tv/writing-on-usb-disks-impossible-on-marshmallow/m-p/2332597#M19347) che non dipende da KoD ma da Android che in alcune ROM/Versioni di Android non ha i permessi di scrittura su dispositivi esterni ma solo di lettura, alcune persone hanno raggirato il problema utilizzando https://virtualhere.com/
