### ISSUE TITLE
https://i.dreamsub.cc/ tentativo di phishing bloccato dall'antivirus bit defender

### ISSUE THREAD

**Issue by aandroide** [kodiondemand/addon#380]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)

- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.
![allert](https://user-images.githubusercontent.com/14141574/156258463-1193190b-826a-44d4-9f31-180009ef6b71.PNG)

**Comment by mac12m99** [comment]
E' sicuramente un falso positivo..
Ti ha chiuso kodi?

**Comment by aandroide** [comment]
No non mi ha chiuso Kodi ma semplicemente l'antivirus mi ha bloccato la ricerca del film da solo quella URL

**Comment by mac12m99** [comment]
Mi spiace ma non possiamo fare molto.. non puoi aggiungere kodi o quell'url ad una lista delle esclusioni (se c'è)?

**Comment by aandroide** [comment]
Si posso farlo. Mi ero un'attimo allertato visto gli attacchi recenti hacker.
Volevo solo una vostra valutazione se si può continuare ad utilizzare o se è meglio metterlo offline.

**Comment by mac12m99** [comment]
Io non ci vedo nessuna minaccia, oltretutto visitare un sito da KoD è diverso in quanto la pagina viene analizzata e non interpretata come avviene nei browser (con conseguente esecuzione di codice javascript).
Riuscire ad infettare attraverso KoD la vedo molto dura.
