### ISSUE TITLE
Sport

### ISSUE THREAD

**Issue by Githeo** [kodiondemand/addon#381]
Salve,

ho notato che, rispetto ad altri addon, non proponete una sezione "sport".
Mi domandavo se una tale sezione è pianificata nel futuro o se, per scelta, non sarà aggiunta.

Grazie.

**Comment by mac12m99** [comment]
Salve, mi spiace ma la sezione sport non è mai stata inserita sia per scelta che per disinteresse all'argomento da parte degli sviluppatori.
