### ISSUE TITLE
ilcorsaronero

### ISSUE THREAD

**Issue by Dummy53** [kodiondemand/addon#382]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale
ilcorsaronero

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)
il link "ilcorsaronero.link" NON funziona. Deve essere sostituito con "ilcorsaronero.in"
- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.

**Comment by mac12m99** [comment]
Il corsaro che problema ha? Per favore descrivi, sembrerebbe andare.. 
Non è che l'hai provato in un momento in cui era offline?

**Comment by Dummy53** [comment]
Il link "ilcorsaronero.link" è offline da giorni. Ho sostituito manualmente con "ilcorsaronero.in" nei files "channels.json" di KOD e "providers.json" di elementum in KODI 19.4 win e funziona ma non è possibile farlo in Android TV. Occorre un aggiornamento. Grazie

**Comment by Dummy53** [comment]
Anche la pagina web "ilcorsaronero.link" è offline come segnalato anche da KOD

**Comment by mac12m99** [comment]
Adesso in effetti è offline, comunque il .in è probabilmente un clone in quanto ci sono riferimenti ad altadefinizione (non presenti nell'originale). 
Forse i torrent li presenti sono gli stessi ma non è lo stesso sito, è qualcun'altro che si spaccia per loro.
Stiamo comunque aggiungendo www.1337x.to come alternativa, ormai ilcorsaro è più offline che online..

**Comment by morisgroves** [comment]
> Adesso in effetti è offline, comunque il .in è probabilmente un clone in quanto ci sono riferimenti ad altadefinizione (non presenti nell'originale). Forse i torrent li presenti sono gli stessi ma non è lo stesso sito, è qualcun'altro che si spaccia per loro. Stiamo comunque aggiungendo [www.1337x.to](http://www.1337x.to) come alternativa, ormai ilcorsaro è più offline che online..

ciao! ma è già stato inserito? vedo che è nella lista dei canali all'interno del codice ma in KOD non lo trovo. grazie

**Comment by mac12m99** [comment]
E' presente solo nella versione beta al momento, in quanto dobbiamo pensare bene come gestire la presenza di contenuti in altre lingue, in particolare nella ricerca (e poi realizzare ciò)
