### ISSUE TITLE
Crash su Manjaro ARM 64bit

### ISSUE THREAD

**Issue by ironmic** [kodiondemand/addon#384]
Ciao, vi segnalo che KoD pare abbia problemi di compatibilità con Kodi 19.4 su Manjaro XFCE ARM 64bit (Raspberry Pi 4).

Senza nessuna particolare configurazione di Kodi o KoD entrando nell'addon e cliccando su qualsiasi voce di menu (compreso settings e help) l'applicazione va in crash.

Riporto il log competo di Kodi se può essere utile per un'analisi (anche se non sembra evidenziare la causa del crash):
[kodi_crashlog-20220425_113417.log](https://github.com/kodiondemand/addon/files/8553395/kodi_crashlog-20220425_113417.log)

Se c'è qualche test che posso fare per approfondire il problema fatemi sapere.
Grazie

**Comment by mac12m99** [comment]
Ciao,
potresti indicarmi la versione completa di python?
python --version
Ho il sospetto riguardi questo bug: https://bugs.python.org/issue46070

**Comment by ironmic** [comment]
Ciao,
versione python 3.10.4
Grazie

**Comment by mac12m99** [comment]
Giusto un altro mi segnala lo stesso problema con la stessa versione di python, potresti provare a fare il downgrade alla versione 3.9?

**Comment by ironmic** [comment]
Ci provo e poi ti aggiorno.
A presto

**Comment by ironmic** [comment]
Non potendo fare il downgrade della versione python di sistema stavo provando con pyenv:

`pyenv exec python --version`
Python 3.9.11
`pyenv exec kodi`

Kodi si avvia ma temo che l'addon KoD me lo esegue ancora sulla v3.10 di sistema..
Per caso sai se è possibile forzare l'esecuzione dello script "default.py" dell'addon specificando il path assoluto della mia versione 3.9 di python anziché quella di sistema (/usr/bin/python)?

**Comment by mac12m99** [comment]
Sicuramente con dei magheggi si può fare, tuttavia non credo valga la pena provare, se installare la 3.9 non è possibile prova piuttosto a fare il downgrade o alla 3.10.0 o alla 3.10.2, queste 2 pare non abbiano questo problema.
https://wiki.manjaro.org/index.php/Downgrading_packages

**Comment by ironmic** [comment]
Purtroppo non funziona quella modalità di downgrade (l'avevo già provata ma non esiste il pacchetto downgrade nel repo ufficiale), inoltre sto scoprendo ora che nella versione ARM di Arch Linux pare che non esista un archivio dei vecchi pacchetti compilati quindi forse mi rimane solo la strada di ricompilazione dai sorgenti python.

Mi prendo del tempo per approfondire un po' le questione e ti aggiorno se riesco ad eseguire quel test con un'altra versione di python.
Grazie

**Comment by ironmic** [comment]
Il problema è rientrato con python v3.10.5.
Chiudo la segnalazione.
