### ISSUE TITLE
Crash su Manjaro x86_64

### ISSUE THREAD

**Issue by ultimoistante** [kodiondemand/addon#385]
Ciao, vi segnalo che il crash segnalato da **ironmic** (https://github.com/kodiondemand/addon/issues/384) si verifica anche su architettura x86_64.
Confermo la stessa versione python: **3.10.4**

Allego un crash log, completo di output gdb.
[kodi_crashlog-20220509_105331.log](https://github.com/kodiondemand/addon/files/8650254/kodi_crashlog-20220509_105331.log)

Se posso essere d'aiuto in qualsiasi modo, chiedete pure.

Grazie

**Comment by mac12m99** [comment]
Ciao,
con la versione 3.10.5 sembra essere tutto risolto, chiudo.
Se non dovesse essere così, riapri pure.

**Comment by ultimoistante** [comment]
ottimo, confermo: tutto perfettamente funzionante, versione python 3.10.5
