### ISSUE TITLE
ilcorsaronero - Serie TV

### ISSUE THREAD

**Issue by morisgroves** [kodiondemand/addon#389]
Ciao ragazzi, prima di tutto grazie!
Nel canale ilcorsaronero sembrerebbe funzionare tutto correttamente tranne la sezione Serie TV.

**Comment by Alhaziel01** [comment]
Prova la beta e fammi sapere se è stato risolto

**Comment by morisgroves** [comment]
Scusate ma sono rientrato alla base solo ieri.
Sì confermo che con la versione Master (Beta) funziona correttamente, grandi come sempre!
