### ISSUE TITLE
AnimeSaturn numerazione episodi sbagliata

### ISSUE THREAD

**Issue by DarkSkull91** [kodiondemand/addon#390]
Non so se sia un problema solo di questo canale o in generale, fatto sta che selezionando l'episodio 10 di Bleach (ITA) viene avviato lo streaming del 100simo.
Ho controllato sul sito ed è presente il corretto episodio.
Viene fatto un ordinamento a livello di stringa piuttosto che a livello numerico.

**Comment by Alhaziel01** [comment]
Sii più preciso, da canale o da libreria/videoteca? ITA o SUB-ITA?
Ho appena provato da canale e avvia l'episodio corretto.

**Comment by DarkSkull91** [comment]
Questo comportamento l'ho riscontrato da videoteca, cliccando su TV Shows dalla home di Kodi.
Parlo di Bleach in italiano non sottotitolato.

**Comment by DarkSkull91** [comment]
Ho ricontrollato anche facendo partire l'episodio da KOD non dalla videoteca presente nel menu principale di Kodi.
E partono episodi a caso, ovvero: faccio partire la 12 parte la 120, 13 -> 139 e 14 -> 146.

C'è qualche problema con l'ordinamento.

**Comment by mac12m99** [comment]
Fixato da https://github.com/kodiondemand/addon/issues/393
