### ISSUE TITLE
Nessun risultato nelle ricerche generali su Xbox Series S

### ISSUE THREAD

**Issue by Elvitek** [kodiondemand/addon#396]
Scusate ragazzi ma come mai su Xbox Series S, se si cerca un film o serie tv, nella ricerca generale, dopo aver scelto il film nel menù delle locandine, non trova nessun risultato? Nella ricerca, scorrono i secondi, come se sta cercando ma scorrono all'infinito senza trovare nessun risultato, rimane quel 0 su 18 e tutto questo succede dopo gli ultimi due update. Potete risolvere il problema? Grazie.

**Comment by mac12m99** [comment]
Ciao,
purtroppo non abbiamo una Xbox per testare, per favore manda il log
https://telegra.ph/LOG-11-20

**Comment by Elvitek** [comment]
Vi lascio due link del log, sperando di averlo fatto bene perché da Xbox è un po' così non potendo copiare un testo, quindi ho utilizzato il terzo metodo.

Vi do più info durante la fase di log dato che questa volta sono riuscito a cercare un film ma mettendoci MOLTO tempo:

Come vedrete ho aperto KOD, cercato il film "Una Notte da Leoni", mi è apparsa subito la schermata con le locandine dei tre film, quindi "Una Notte da Leone 1, 2 e 3" e una volta selezionato il primo, ci ha messo esattamente 300 secondi per cercare i primi 6/17 risultati e 469 secondi per cercarli in tutti i canali tanto da fare il 17/17, ho avviato un link per vedere se funzionava e tutto ok. Poi ho voluto provare con il secondo film, sono andato a cliccare la locandina del secondo e ci ha messo circa 20 secondi per fare il risultato 17/17, stessa cosa per il terzo film, sempre sui 20 secondi tutto, quindi alla fine, è come se dovesse caricare una volta tutti i canali mettendoci quel tempo ma per le altre ricerche, ha le cache caricate per farlo in fretta. Ora non c'è nel log ma ieri ho provato a cercare un nuovo film dopo sia la ricerca lunga di 400 secondi e sia quella di 20 e di nuovo ci mette 400 secondi per cercare un nuovo film. Spero si riesca a capire qualcosa per risolvere il tutto e altra cosa, se può servire, ci mette tanto anche ad aprire quei menù per la digitazione del contenuto da cercare e sia il menù delle impostazioni di KOD, quindi quei menù a "pop up". Attendo una risposta, grazie.

https://paste.kodi.tv/xojaj

**Comment by mac12m99** [comment]
Purtroppo hai saltato il primo passo: abilitare l'opzione "Logging di Debug" nelle impostazioni dell'addon, il log che hai generato non ha abbastanza info per capire il problema, potresti rifarlo con questa opzione abilitata?

**Comment by Elvitek** [comment]
[LOG594087132.log.txt](https://github.com/kodiondemand/addon/files/9601431/LOG132.log.txt)

Ecco qui. Ho eseguito sia la ricerca dei 3 "Una Notte da Leoni" con la prima ricerca da 400 secondi e le altre due da 7 secondi nel menù delle locandine e poi, ho cercato un nuovo film, "Shrek", con di nuovo i famosi 400 secondi.

**Comment by mac12m99** [comment]
Alla base credo ci sia un bug nell'implementazione di python su Xbox.. comunque ho trovato dove si "blocca" ed ho fatto una modifica che potrebbe risolvere.
Per provarla installa la versione beta senza disinstallare l'addon (basta che ri-installi KoD-Installer e scegli master, non perderai nulla).
Fammi sapere se funziona.

**Comment by Elvitek** [comment]
Allora, dopo aver installato la versione master, alla prima ricerca dei soliti 3 film nel menù delle locandine (Una Notte da Leoni 1, 2 e 3), i primi 7 risultati li ha trovati in circa 30 secondi ma sono tutti torrent e solo 3 erano siti "veri" ma comunque c'è un piccolo progresso, mentre il 17/17 lo ha completato in 450 secondi. La seconda ricerca in 34 secondi, mentre la terza in 17 secondi. Poi ho cercato di nuovo Shrek e ha trovato i primi 7 in 30 secondi ed il 17/17 in 409 secondi, più o meno come prima. Detto questo, il problema è sempre lo stesso e ciò che alla prima ricerca fa fatica ma se un film ha un trilogia o più e quindi nel menù delle locandine ci sono più film, la seconda ricerca scegliendo ad esempio il 2, sarà molto più veloce facendo il 17/17 in sotto i 30 secondi.

**Comment by mac12m99** [comment]
Ho fatto un'altra prova, se sei rimasto sulla beta dovresti ricevere l'aggiornamento, fammi sapere se noti miglioramenti.
Magari manda anche il log, così vedo se ci sono ancora punti dove si blocca.

**Comment by Elvitek** [comment]
Molto, molto meglio! Primo risultato dei primi "3 film", 17/17 in 35 secondi, secondo 17/17 in 12 secondi e terzo 17/17 in 16 secondi. Poi ho riprovato con Shrek e ci ha messo 24 secondi per fare 17/17.

Risolto alla grande, grazie mille e l'unica parte dove va lento è quando si clicca una voce nei menù, ad esempio se premo sula voce "ricerca globale", per arrivare alla prossima schermata ci mette tipo 15 secondi, non è immediato come sulla mia box android da 2 gb di ram che ne ha comunque pochi rispetto alla Series S, oppure, ci mette molto quando si preme sulla voce "cerca film", ci mette sempre quei 15 secondi prima che esca la tastiera per scrivere il titolo ma questo credo sia un problema di Kodi stesso, o almeno parlo da ignorante.

Se può servire, ti mando un altro log, altrimenti per me va bene così, dimmi tu ed intanto ti ringrazio per il supporto.

Una cosa, queste modifiche verranno implementate nella prossima versione stabile? Lo chiedo così da sapere quando potrò togliere la beta.

**Comment by mac12m99** [comment]
> Molto, molto meglio! Primo risultato dei primi "3 film", 17/17 in 35 secondi, secondo 17/17 in 12 secondi e terzo 17/17 in 16 secondi. Poi ho riprovato con Shrek e ci ha messo 24 secondi per fare 17/17.

Ottimo! Considera che se rifari la ricerca selezionando un'altro risultato, ha già tutti i moduli dei canali caricati in memoria ed è normale ci metta di meno, poi dipende anche da quanto ci mettono a rispondere i siti (varia da volta a volta)
> 
> Risolto alla grande, grazie mille e l'unica parte dove va lento è quando si clicca una voce nei menù, ad esempio se premo sula voce "ricerca globale", per arrivare alla prossima schermata ci mette tipo 15 secondi, non è immediato come sulla mia box android da 2 gb di ram che ne ha comunque pochi rispetto alla Series S, oppure, ci mette molto quando si preme sulla voce "cerca film", ci mette sempre quei 15 secondi prima che esca la tastiera per scrivere il titolo ma questo credo sia un problema di Kodi stesso, o almeno parlo da ignorante.
> 
> Se può servire, ti mando un altro log, altrimenti per me va bene così, dimmi tu ed intanto ti ringrazio per il supporto.
> 

Non è una cosa normale.. anche gli altri addon ci mettono così tanto? manda il log dai, vedo se riesco a capire il motivo -> entra su ricerca globale, fai apri film e poi annulla

> Una cosa, queste modifiche verranno implementate nella prossima versione stabile? Lo chiedo così da sapere quando potrò togliere la beta.

Considerando che non ho ricevuto segnalazioni da chi usa la beta, le ho appena mandate su stabile, però ti chiedo di rimanere ancora sulla beta, per provare eventuali migliorie al caricamento dei menu

**Comment by Elvitek** [comment]
Si, più o meno lo fa con tutti gli addon, chi più secondi, chi meno ma comunque sempre tanto rispetto alle box android che ho avuto.

Comunque sì, resto con la beta ed ecco a te il log, grazie: 

[LOG700321373.log.txt](https://github.com/kodiondemand/addon/files/9638480/LOG703.log.txt)

**Comment by mac12m99** [comment]
[plugin.video.example.zip](https://github.com/kodiondemand/addon/files/9638620/plugin.video.example.zip)
Potresti installare questo addon di test e dirmi che risultati ottieni? E' un semplice benchmark della lettura dei file

**Comment by Elvitek** [comment]
vfs read: 0.22099876403808594
py read: 0.331010103225708

**Comment by Elvitek** [comment]
@mac12m99 serve altro per risolvere questo problema o posso chiudere? Questo aggiornamento è stato implementato nella versione stabile? Grazie.

**Comment by mac12m99** [comment]
Si è stato implementato, purtroppo per la lentezza di apertura dei menu ci sarebbe da approfondire (anche se come dici, è un problema generale), se intendi tornare alla stabile va bene.

**Comment by Elvitek** [comment]
Perfetto! Allora chiudo e grazie mille per l'aiuto, davvero!
