### ISSUE TITLE
Eurostreaming

### ISSUE THREAD

**Issue by aam1972** [kodiondemand/addon#398]
Quando accedo al canale eurostreaming ottengo un pop up con il seguente errore:

The website eurostreaming.party seems to be unavailable

Ha cambiato in: eurostreaming.quest

Grazie

**Comment by mac12m99** [comment]
Grazie della segnalazione, dominio aggiornato e anche quello di un servizio di url shortening che usa il sito, mi sono reso conto però che gli ultimi contenuti contengono un nuovo server e molti link con il captcha, quindi è probabile che non ci saranno molti server funzionanti, al momento.

**Comment by aam1972** [comment]
Resolved
