### ISSUE TITLE
Crash di Kodi dopo seconda ricerca per titolo

### ISSUE THREAD

**Issue by thegreatyellow67** [kodiondemand/addon#399]
Salve a tutti, apro questo nuovo issue nella speranza che possiate aiutarmi con un problema relativo al vostro addon.
Uso linux mint LMDE5 edition, versione di python 3.9.2, hardware abbastanza datato, piattaforma intel e scheda video NVIDIA GT1030.

Dunque, quando effettuo una ricerca per titolo, la prima volta funziona tutto correttamente, se esco dai contenuti trovati e voglio rifare un'altra ricerca, kodi crasha. La stessa cosa accade in Linux Mint 20.3 con Kodi installato dal repository ufficiale tramite PPA. Per essere maggiormente di aiuto invio il log di crash di Kodi.

[kodi_crashlog-20221027_203536.log](https://github.com/kodiondemand/addon/files/9882313/kodi_crashlog-20221027_203536.log)

Grazie a chiunque possa aiutarmi.

**Comment by mac12m99** [comment]
Salve,
sembrerebbe qualcosa legato alla libreria numpy, che viene usata da KoD solo come dipendenza di js2py (che comunque viene usata pochissimo).
Questo crash accade anche quando non ha mandato nulla in riproduzione? In tal caso prova a togliere animesaturn dalla lista dei canali da includere nella ricerca
Per avere più info, attiva anche il logging di debug dalle impostazioni dell'addon e il debug di kodi, poi oltre al crashlog manda anche il kodi.log

**Comment by thegreatyellow67** [comment]
Perfetto, grazie mille per la risposta. Avendo disattivato animesaturn dalla lista dei canali di ricerca e ripetendo più ricerche, ora kodi non va in crash e questo è positivo. Lo terrò sotto controllo e se si ripeteranno eventuali crash fornirò, come richiesto, i log del caso.

**Comment by mac12m99** [comment]
Ottimo, quindi se lo reinserisci ritorna a crashare? 
Comunque js2py per animesaturn non serve più quindi potrei anche togliere l'import per evitare di fartelo togliere dalla ricerca.
Tuttavia, la causa "radice" è ancora ignota, ci sono altre parti dove viene richiamato il modulo in questione, pertanto c'è da presumere che ti campiterà altre volte in altri modi (ad esempio segnalo che viene usato anche dai server mystream, streamtape e uptobox).
Non è che riusciresti a mandarmi tutti i log? Forse riesco a capire meglio che succede
