### ISSUE TITLE
Rai 1

### ISSUE THREAD

**Issue by ghost** [kodiondemand/addon#402]
Rai 1

- Rai 1 funziona per qualche minuto, dopodiché torna in automatico sulla lista canali, c'è una soluzione? 
Solo Rai 1, tutti gli altri canali funzionano perfettamente

**Comment by ghost** [comment]
Il log è questo:
https://anonfiles.com/C80960I0ye

**Comment by IridiumXOR** [comment]
Ho lo stesso identico problema
[https://anonfiles.com/E7Idr4ibza](https://anonfiles.com/E7Idr4ibza)

**Comment by ilmich** [comment]
Fixato con https://github.com/kodiondemand/addon/pull/463
