### ISSUE TITLE
Dreamsun è di nuovo disponibile 

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#403]
Salve @mac12m99 @Alhaziel01 ho visto che il sito Dreamsub ha riaperto in un altro dominio, potete vedere se è possibile aggiungerlo a kod? Grazie Mille

Dreamsub Link:
https://dreamsubanime.com/

**Comment by mac12m99** [comment]
Ciao,
non sono molto convinto siano gli stessi.. il sito che hai linkato utilizza gli stessi server di animesaturn
Comunque sia, siccome l'unica fonte è la stessa di animesaturn (che è presente su KoD), ha poco senso inserirlo (e non è una cosa che viene gratis, il vecchio scraper di dreamsub non funziona con quel sito, è proprio strutturalmente differente).

Grazie comunque della segnalazione :)

**Comment by Yoshinizar** [comment]
Ok grazie, per non aprire un altro post scrivo qui un altro problemino.
La sezione film di Aniplay non funzionano su kod, tipo Broly di dragon ball il film ed altri, mi dice nulla da riprodurre.
Poi su Aniplay lo switch delle risoluzioni, non me li fa selezionare, ad esempio my Hero accademia stagione 5 episodio 12, e One piece episodio 981, ci sono diverse risoluzioni da selezionare sul sito Aniplay, ma su kod ne da solo uno, confermo che ho settato da due anni tutto su alto sia su kod che su inputstream adaptive con l'opzione di selezione manuale, e mi è sempre funzionato, ma su Aniplay con kod nada, One piece parte a 1080p anche se Ci sarebbero 720/480 ma non selezionabili,...invece My Hero parte a 720 nonostante ci sia 1080, ho provato sia diretto, built, e gli altri, ma è bloccato (1/1) , con Mediaset spunta 3/3 e posso switcharli a conferma che ho i settaggi giusti e la mia connessione va a 900mb. Grazie

**Comment by Yoshinizar** [comment]
Grazie di cuore adesso funziona tutto ciò che ho elencato
