### ISSUE TITLE
Ilcorsaronero.link

### ISSUE THREAD

**Issue by Sardinia1989** [kodiondemand/addon#410]
Il sito ilcorsaronero.link non sembra essere disponibile riprova più tardi. Kodiondemand.

**Comment by xXTimmy89Xx** [comment]
Attualmente ilcorsaronero.link sembra essere non funzionante di conseguenza nemmeno il relativo canale su KoD, non resta che attendere che il sito torni up.

**Comment by xXTimmy89Xx** [comment]
Ciao @Sardinia1989, attualmente il sito ilcorsaronero.link sembra essere down di conseguenza non funziona nemmeno il relativo canale su KoD, non resta che attendere che il sito torni up.

**Comment by xXTimmy89Xx** [comment]
Ciao @Sardinia1989, attualmente il sito ilcorsaronero.link sembra essere down di conseguenza non funziona nemmeno il relativo canale su KoD, non resta che attendere che il sito torni up.

**Comment by Sardinia1989** [comment]
Grazie mille,  per l'informazione

Il Mer 25 Gen 2023, 20:44 Timmy89 ***@***.***> ha scritto:
