### ISSUE TITLE
Real Debrid

### ISSUE THREAD

**Issue by Pietro395** [kodiondemand/addon#412]
Ciao,
Vedo che si KOD è possibile autenticare un servizio di debrid come Real Debrid, non mi è chiaro però che token viene richiesto, il processo di autenticazione di un dispositivo prevede aprire la pagina https://real-debrid.com/device e inserire il codice visualizzato nell'addon

**Comment by xXTimmy89Xx** [comment]
Ciao @skar395 Il token per l'autenticazione dovrebbe essere reperibile da qui https://real-debrid.com/apitoken

**Comment by xXTimmy89Xx** [comment]
> Ciao, Vedo che si KOD è possibile autenticare un servizio di debrid come Real Debrid, non mi è chiaro però che token viene richiesto, il processo di autenticazione di un dispositivo prevede aprire la pagina https://real-debrid.com/device e inserire il codice visualizzato nell'addon

Ciao @skar395 Il token per l'autenticazione dovrebbe essere reperibile da qui https://real-debrid.com/apitoken
