### ISSUE TITLE
KOD e distinzione TV/Movie per TMDB

### ISSUE THREAD

**Issue by InvisibleKnight** [kodiondemand/addon#413]
Sto avendo problemi con l'integrazione Trakt di KOD e la gestione del TMDB_ID. 

Utilizzo l'addon Trakt ufficiale scaricato dalla repository di kodi.

Quando, per esempio, da KOD vado in "serie più popolari" e guardo The Last of Us. La serie sarà correttamente individuata con ID 100088. 

ma invece di https://www.themoviedb.org/tv/100088 
Trakt registra https://www.themoviedb.org/movie/100088

Ovvero stesso numero identificativo ma nella categoria Movies. Ad ulteriore testimonianza di ciò i film vengono identificati correttamente in KOD: ID corretto nella corretta sezione MOVIES. 

Da Jellyfin/plex Trakt individua correttamente sia le serie TV che i film. 

In qualche modo Trakt da KOD riceve il TMDB_ID ma non fa la distinzione tra TV e MOVIES.

**Comment by mac12m99** [comment]
Ho provato con la stessa serie e sia riproducendola dalla ricerca che aggiungendola in videoteca e poi riproducendo un episodio: viene segnata correttamente
Forse hanno fatto qualche modifica su tmdb e ora funziona, riprova per favore.
Se non dovesse funzionare dimmi da che canale lo aggiungi/guardi.

Non dovrebbe centrare ma noto comunque che KoD non gli passa l'id di tvdb e che il titolo trakt lo vuole come slug, ho già pronte le modifiche ma prima vorrei investigare meglio

**Comment by InvisibleKnight** [comment]
> Ho provato con la stessa serie e sia riproducendola dalla ricerca che aggiungendola in videoteca e poi riproducendo un episodio: viene segnata correttamente Forse hanno fatto qualche modifica su tmdb e ora funziona, riprova per favore. Se non dovesse funzionare dimmi da che canale lo aggiungi/guardi.
> 
> Non dovrebbe centrare ma noto comunque che KoD non gli passa l'id di tvdb e che il titolo trakt lo vuole come slug, ho già pronte le modifiche ma prima vorrei investigare meglio

Ho testato Cineblog e Filmpertutti, entrambi danno lo stesso risultato menzionato nel post iniziale. Riproduco tutto da ricerca. 

Fammi sapere cosa può servirti per approfondire.

**Comment by xXTimmy89Xx** [comment]
La maggior parte dei problemi dovrebbero essere stati corretti con il rilascio della versione 3.6.1
