### ISSUE TITLE
CB01 NON FUNZIONANTE SU KODI

### ISSUE THREAD

**Issue by daryldix89** [kodiondemand/addon#416]
CB01 

- E' da un paio di settimane che su Kodi il canale CB01 non riesce a trovare sia i film aggiunti che quelli aggiornati sebbene il sito sia perfettamente funzionante su pc e smartphone. Non mi da alcun errore solo la scritta nessun elemento in lista

**Comment by italfire** [comment]
Credo sia un problema nella tua installazione. CB01 funziona perfettamente. Prova a disinstallare e reinstallare  tutto nuovamente.

**Comment by daryldix89** [comment]
> Credo sia un problema nella tua installazione. CB01 funziona perfettamente. Prova a disinstallare e reinstallare tutto nuovamente.

no ho provato e reinstallato non funziona ne su pc, ne in televisione, in pratica due sezioni di cb01 come ultimi film aggiunti e aggiornati non ti da alcun risultato. Se cerco i film singolarmente si, quindi non so se è un problema di server. Se a te funziona probabilmente è la versione installata kodi 20 nexus

**Comment by italfire** [comment]
Posso assicurarti che su Matrix funziona perfettamente non ho provato Nexus

**Comment by mac12m99** [comment]
Le sezioni:
- film: Ultimi Aggiornati
- film: Ultimi Aggiunti
- serietv: Ultime Aggiornate
Non sono più presenti sul sito (ed è per questo che davano "nessun elemento da visualizzare"), le ho quindi eliminate. Per quanto riguarda le serie ho aggiunto "Ultime Aggiunte" dato che veniva gratis.

Grazie della segnalazione :+1:
