### ISSUE TITLE
Supervideo

### ISSUE THREAD

**Issue by sangiac** [kodiondemand/addon#418]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del server che indica problemi e se il problema è circoscritto ad un solo canale, indicalo
Supervideo

- Allega il file di log nella sua completezza. Non cancellarne delle parti.
https://anonfiles.com/sbSaDdl5z6

**Comment by mac12m99** [comment]
Corretto con 66ae64c5620c1c2972f72d728117df5e9c93ed09
