### ISSUE TITLE
eurostreaming.taxi

### ISSUE THREAD

**Issue by Paolosalp** [kodiondemand/addon#420]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

eurostreaming.taxi  da diversi giorni non è disponibile - 
- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.

**Comment by xXTimmy89Xx** [comment]
Il sito in questione aveva cambiato dominio da .taxi a ,care, il fix dovrebbe essere già stato mandato.

**Comment by Paolosalp** [comment]
Ok grazie
