### ISSUE TITLE
Trailer

### ISSUE THREAD

**Issue by italfire** [kodiondemand/addon#421]
Salve, da un paio di giorni non riesco piu a vedere un trailer senza che si blocchi o peggio non parte . Delle volte compare una finestra che mi dice di controllare via browser clicco ok e  infatti nel browser funziona perfettamente . Credo ci sia un problema nel server oppure dell'addon youtube.

**Comment by xXTimmy89Xx** [comment]
Situazione attuale sulla funzione cerca trailer di KoD, dal momento che molti di voi stanno riscontrando il problema e lo stanno segnalando cerchiamo di fare un attimo chiarezza, il problema non è legato a KoD ma all'addon YouTube stesso dipendenza necessaria per far funzionare correttamente la funzione in questione, gli sviluppatori dell'addon YouTube stesso hanno già provveduto al fix che verrà rilasciato ufficialmente con la versione finale 7.0.2, al momento nella pagina ufficiale di github è disponibile la versione 7.0.2.alpha7 con il fix parziale ma personalmente consigliamo di attendere il rilascio della versione stabile.
