### ISSUE TITLE
IlCorsaroNero

### ISSUE THREAD

**Issue by Dummy53** [kodiondemand/addon#424]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

**IlCorsaroNero**

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)
**Le liste film e serie TV sono vuote**
- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.

**Comment by mac12m99** [comment]
Corretto con f470c49c7b91724654717f1b976da5e1389f9fb8
