### ISSUE TITLE
MediasePlay

### ISSUE THREAD

**Issue by italfire** [kodiondemand/addon#427]
Salve, e complimenti per l'ottimo lavoro che svolgete. Volevo segnalare che in Mediaset Play la voce '_Soap e Telenovela_' prima disponibile nel menu di '_Fiction/Serie TV_'  ora non e più visibile. Sareste cosi gentili da ripristinarla se e possibile  e molto comoda per i miei altrimenti si e costretti sempre a fare una ricerca. Grazie infinitamente

**Comment by xXTimmy89Xx** [comment]
Sezione aggiunta/ripristinata con il commit
