### ISSUE TITLE
StreamSB

### ISSUE THREAD

**Issue by sangiac** [kodiondemand/addon#428]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

StreamSB

non parte video ma in Browser ( Google Chrome ) parte regolarmente

https://anonfiles.com/bdtfSex8zf

- [ ] https://anonfiles.com/bdtfSex8zf

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)

- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.

**Comment by mac12m99** [comment]
Dovrebbe essere risolto con 76550bcebb41d10fdd1925010b81c99fbc101e9b
