### ISSUE TITLE
Cb01

### ISSUE THREAD

**Issue by Jobbe1978** [kodiondemand/addon#431]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Ciao ragazzi,

sul canale CB01, noto che è impossibile far partire i link di alcune serie tv se queste sono collegate tramite il provider Uprot.net

tipo qui: https://uprot.net/msfld/5q1mohng4091

Ieri stavo cercando la serie tv "Hello Ladies" (disponibile qui https://cb01.training/serietv/hello-ladies/)

Da Kodi, riesce a visualizzare il canale CB01 che contiene la serie tv, ma cliccando su ogni episodio mi restituisce errore, quando invece da pc mi apre il link uprot e poi da lì riesco a vedere ogni puntata.

Riuscite a fixare?

grazie mille!

**Comment by xXTimmy89Xx** [comment]
https://github.com/kodiondemand/addon/issues/357
