### ISSUE TITLE
IlCorsaroNero errore sistemi Android

### ISSUE THREAD

**Issue by Dummy53** [kodiondemand/addon#432]
Nei sistemi Android e Android TV viene riportato errore nell'aprire qualsiasi lista files (Bdrip, DVD ecc..) mentre nell'installazione Windows di Kodi funziona tutto regolarmente.
Grazie dell'attenzione

**Comment by xXTimmy89Xx** [comment]
Ciao @Dummy53, siamo consapevoli del problema, non ti resta che attendere il fix che potrebbe tardare causa periodo estivo.

**Comment by Dummy53** [comment]
Grazie, aspetto

**Comment by xXTimmy89Xx** [comment]
> Grazie, aspetto

E' stato appena rilasciato il fix per il problema in questione commit 353281d.
