### ISSUE TITLE
Toonitalia non va...

### ISSUE THREAD

**Issue by dvdmnc81** [kodiondemand/addon#433]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)

- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.

**Comment by dvdmnc81** [comment]
Toonitalia ha un nuovo indirizzo: https://toonitalia.green e quindi toonitalia.xyz non funziona più. Correggete il link per favore. Grazie mille

**Comment by xXTimmy89Xx** [comment]
Il dominio https://toonitalia.green/ non è il dominio ufficiale ma un sito clone/fake il domino ufficiale è e rimane https://toonitalia.xyz/, purtroppo il sito in questione ha cambiato completamente struttura e necessita di un fix.
