### ISSUE TITLE
Problema Sync tra Videoteca Kod e Libreria Kodi

### ISSUE THREAD

**Issue by Crilor** [kodiondemand/addon#434]
Vi scrivo perché + volte questo problema mi si è presentato e più volte non ho trovato altra soluzione  che azzerare Kodi e ricominciare.

Il problema si presenta rispetti mente su un televisore Philips Android TV e su un Google TV.

In sostanza dopo poche settimane che uso il programma il problema che si presenta è che la libreria di Kodi non si sincronizza più Co. La videoteca di Kod: le nuove puntate delle serie appaiono nella videoteca Kod ma non nella libreria e così vale anche per le Nuove serie aggiunte e i film aggiunti.
HELP!

**Comment by xXTimmy89Xx** [comment]
Ciao @Crilor come affrontato più volte nel canale di supporto Telegram è un problema degli scraper che si occupano di recuperare le informazioni per i film e le serie tv per la libreria di kodi, attualmente gli scraper predefiniti di Kodi sono per i Film The Movie Database Python e per le Serie TV TMDb TV Shows, i vecchi scraper The Movie Database (XML) sono stati recentemente contrassegnati come non funzionati e disabilitati, verifica come da video nelle impostazioni di KoD nella sezione Videoteca che la voce Aggiunti la videoteca di KoD alla libreria di Kodi sia abilitata e che siano stati selezionati gli scraper correti.

https://github.com/kodiondemand/addon/assets/53865707/9e7dc998-6d82-4596-ba1c-5716cba1814c

**Comment by Crilor** [comment]
Tutto chiaro! Ho provato e sembra aver funzionato. In caso contrario mi rifarò vivo.
Grazie mille siete il top
