### ISSUE TITLE
Mediaset Infinity

### ISSUE THREAD

**Issue by numbernumero** [kodiondemand/addon#438]
Salve, in mediaset molti contenuti sono assenti anche se sono presenti nel sito web.
esempi "Terra Amara sono presenti solo 100 episodi mentre in realta sono 406
Nel sito web di mediaset si possono vedere gli episodi/programmi  trasmessi anche tramite la guida e  anche se trasmmesse solo poche ore prima (Replay).  Sarebbe una cosa gradita a tutti gli utenti che utilizzano questo canale se si potesse aggiungere appunto la sezione Replay come gia presente nel canale  RaiPlay.
Grazie mille per il lavoro che svolgete e spero che possiate trovare il tempo per sistemare questo canale davvero seguitissimo.

**Comment by ilmich** [comment]
fixato dal commit https://github.com/kodiondemand/addon/commit/f2e85c9ae849475afbfdcc6246893c8f30c2c726
