### ISSUE TITLE
StreamingCommunity

### ISSUE THREAD

**Issue by strx24q** [kodiondemand/addon#441]
Salve, il canale streamingcommunity non sembra funzionare, ho visto che anche il link non è l'ultimo aggiornato.
Potreste aggiornarlo per poter raggiungere quei contenuti? 
Grazie.

**Comment by strx24q** [comment]
Grazie ilmich! Ho testato il tuo codice e funziona abbastanza bene! Ho anche avuto bisogno di modificare il modulo del canale.codes in.at (sembra che SC abbia cambiato il suo dominio)

**Comment by ilmich** [comment]
questo a me non è servito perchè il dominio fa il redirect verso quello nuovo. poi dipende anche dal tuo provider chiaramente
