### ISSUE TITLE
altadefinizione, tutti i film non funzionano

### ISSUE THREAD

**Issue by gobsmanola** [kodiondemand/addon#446]
*Buongiorno a tutti , da un po di tempo uso kodi con addon kodiondemand e se prima si vedevano diversi canali adesso non si vedono più. Alta definizione è tanto che non si vede e così Tantifilm e tanti altri.
Magari devo fare qualcosa io. uso una vpn cyber ghost ma se clicco sui canali in questione viene fuori la scritta "successivo", e poi non accade niente. Questo per alta definizione e invece  tantifilm non si visualizza proprio.
ma non sono molto pratica. Vi sarò grata se potrete darmi informazioni. Grazie e buona giornata.

**Comment by xXTimmy89Xx** [comment]
Fixato con il commit 35e051c
