### ISSUE TITLE
Streamingcommunity 

### ISSUE THREAD

**Issue by thormt** [kodiondemand/addon#460]
Aprendo un link di Streamingcommunity (ricerca Happy Day), compare sempre un errore che rimanda a dei log (ma non so dove guardare)

Se apro il link nel browser, funziona senza problemi 

L'attuale stream va su .estate

**Comment by xXTimmy89Xx** [comment]
FIxato con il commit acfd6f628f583278a649fb0bbc33baf9d417e4bf
