### ISSUE TITLE
Ancora problemi con streaming comunity

### ISSUE THREAD

**Issue by Vincenzo-8** [kodiondemand/addon#461]
Ciao a tutti, ho appreso che il problema streaming comunity è stato risolto tuttavia continuo ad avere problemi. Allego il log.

Si tratta di una nuova installazione su macOS fatta appositamente per testare se con un altro dispositivo SC andasse oppure no. Cache ripulita e DNS corretti impostati su modem.

[
[log.txt](https://github.com/kodiondemand/addon/files/14027743/log.txt)
](url)

**Comment by xXTimmy89Xx** [comment]
Fixato con il commit acfd6f628f583278a649fb0bbc33baf9d417e4bf
