### ISSUE TITLE
Aniplay cambio struttura

### ISSUE THREAD

**Issue by Yoshinizar** [kodiondemand/addon#484]
È possibile sistemare il sito https://aniplay.co
Ha cambiato struttura del sito e quindi su kod ondemand non è più funzionante.

Grazie mille

**Comment by xXTimmy89Xx** [comment]
> È possibile sistemare il sito https://aniplay.co Ha cambiato struttura del sito e quindi su kod ondemand non è più funzionante.
> 
> Grazie mille

Il sito sembra ver chiuso.
