### ISSUE TITLE
Rai Play

### ISSUE THREAD

**Issue by italfire** [kodiondemand/addon#487]
Salve il canale RaiPlay sembra non funzionare perfettamente infatti tutti i film in formato 'mpd' non partono. Provato su tutti i miei device "Firestick, Libreelec, Windows 11" mentre sia online (pagina web ufficiale)  che con APK funzionano benissimo.
Per riprodurre il problema dal menu principale del canale :  Film > Star di Hollywood > Legend

**Comment by numbernumero** [comment]
Infatti molti dei link ai film non funzionano per cui  conviene utilizzare l'addon ufficiale RaiPlay, al momento tutti I **film** nell'addon Ufficiale **RaiPLAY** funzionano perfettamente mentre nel canale di RaiPlay in **Kod** moltissimi link ai film non funzionano. Non so se sia dovuto alla loro estensione HLS o MPD fatto sta che molti non funzionano. Ripeto conviene utilizzare l'addon ufficiale RaiPLAY dove al momento funziona tutto. Capisco che entrare ed uscire da piu addon e una rottura ma finche kod non sistema il suo RaiPlay non vedo altre soluzioni.

**Comment by ilmich** [comment]
fixato dal https://github.com/kodiondemand/addon/commit/6c08f820e6010d7e38e4a60c07bcc92249008ddb

grazie per la segnalazione
