### ISSUE TITLE
Link validi per canali mancanti

### ISSUE THREAD

**Issue by IridiumXOR** [kodiondemand/addon#488]
Salve,
[qua](https://github.com/Tundrak/IPTV-Italia) e' presente una lista VLC contenente molti canali mancanti su KoD (come ad esempio Cielo). Puo essere utile per una sua integrazione?

**Comment by ilmich** [comment]
Ciao e grazie per la segnalazione, l'aggiunta di tv8 e cielo è in cantiere. 
Se ci sono altri canali che ti piacerebbe avere per favore segnalali qui https://github.com/kodiondemand/addon/issues/465
