### ISSUE TITLE
Rai Play

### ISSUE THREAD

**Issue by numbernumero** [kodiondemand/addon#490]
Salve,  grazie per lavoro che dedicate a questo progetto siete unici . Volevo segnalarvi che nell'ultimo fix di RaiPlay vi e sfuggito un particolare:
in fondo alle liste delle Serie TV o Programmi e presente una voce '_**Vai a tutti**_' se si clicca su questa, Kod restituisce un errore oppure (raramente) restituisce un messaggio in cui indica di controllare se il link funziona via browser. Provando via browser funziona perfettamente.
 Questo succede sia con le liste delle  Serie TV che nelle liste dei Programmi.
Un esempio per poter riprodure il problema:  '**_Serie italiane_**' poi '**_Serie Originale RaiPlay_**' in fondo alla lista '**_Vai a tutti_**'

**Comment by xXTimmy89Xx** [comment]
> Salve, grazie per lavoro che dedicate a questo progetto siete unici . Volevo segnalarvi che nell'ultimo fix di RaiPlay vi e sfuggito un particolare: in fondo alle liste delle Serie TV o Programmi e presente una voce '_**Vai a tutti**_' se si clicca su questa, Kod restituisce un errore oppure (raramente) restituisce un messaggio in cui indica di controllare se il link funziona via browser. Provando via browser funziona perfettamente. Questo succede sia con le liste delle Serie TV che nelle liste dei Programmi. Un esempio per poter riprodure il problema: '**_Serie italiane_**' poi '**_Serie Originale RaiPlay_**' in fondo alla lista '**_Vai a tutti_**'

Fixato due mesi fa con il commit cc0f047c284c001bc9855e09d36f8506874ecd27
