### ISSUE TITLE
Mediaset

### ISSUE THREAD

**Issue by numbernumero** [kodiondemand/addon#491]
Salve nelle ultime modifiche al canale sono scomparsi i menu delle serie tv. Cortesemente potete affiungere il Menu delle Soap Opera o almeno potete gentilmente darmi il link tipo  "{'uxReference':'.......................................'},"  in modo da poterlo inserire in locale nel menu sotto la stringa delle serie TV.  Esempio **('Fiction / Serie TV {bullet bold}', ['/fiction', 'peliculas', {'uxReference':'SoapOpera............???'}, 'tvshow'])**,.
Grazie 1000 in anticipo

**Comment by irontes** [comment]
anche a me interessa avere il menu delle serie TV e sopratutto delle Soap.
Hai provato {'uxReference':'SoapDelMomento'} ?

**Comment by xXTimmy89Xx** [comment]
Sezione aggiunta con il commit a683419
