### ISSUE TITLE
Kodi non si termina mai. Rimane freezato nella schermata di chiusura. Dettagli spiegati all'interno.... grazie in anticipo.

### ISSUE THREAD

**Issue by DjDiabolik** [kodiondemand/addon#497]
Allora amici sto riscontrando questo piccolo problema che causa la non corretta chiusura di KODI stesso dopo l'uso e la visione di un video.
Ne vorrei discutere anche con Voi o cmq anche da queste parti perchè in qualche modo anche KOD ne entra in gioco e ora vi spiego perchè.

Partiamo col dire che uso KOD su una postazione Mini pc con su UBUNTU 22.04.4 LTS. Ovviamente sistema in italiano la gui di kodi in italiano ecc ecc.
La versione di KODI è l'attuale 21 in versione FLATPAK...... la Skin (che sembra essere afflitta dal problema poi spiegherò il perchè) è la "Estuary MOD V2" dalla repo di KodiNerds.

Veniamo alla descrizione del problema:
Allora inizialmente è ben dire e specificare che ho iniziato a notare la cosa dopo aver aggiornato il mio addons Youtube alla 7.0.8 beta 4 dalla repository di anxdpanic qua:
https://github.com/anxdpanic/plugin.video.youtube/releases/tag/v7.0.8%2Bbeta.4

Subito dopo aver aggiornato a questa versione e visto alcuni video Youtube sono andato a chiudere KODI e notato che rimane bloccato alla schermata di chiusura senza mai sbloccarsi.... atteso anche 30 minuti ma niente c'è da killare il suo processo brutalmente in qualche modo. Questo succedeva esattamente ieri sera nel tardo pomeriggio.

Pochi minuti fa invece ho fatto qualche prova e ho scoperto quindi che:
- Disattivando KOD e riavviando KODI. Aprendo un qualsiasi video youtube il problema segnalato sopra scompare.
- Se dalle versioni disponibili dell'addons youtube faccio un salto indietro alla beta 3 il problema non si presenta

Dopo svariati avvi e riavvi di Kodi per testare questa cosa ho anche scoperto che SE CAMBIO LA SKIN e passo alla STOCK e originale Estuary usando appunto la beta 4 dell'addons kodi e mantenendo attivo allo stesso tempo anche KOD questo problema non si presenta e kodi si termina correttamente.

Ora come possiamo vedere entrano in gioco diversi fattori di contro, forse erroneamente, avevo aperto un issue proprio relativo all'addons youtube qua:
https://github.com/anxdpanic/plugin.video.youtube/issues/813
Ma con le ultime scoperte appena descritte sopra devo dire che non posso dire che la colpa sia effettivamente l'addons di youtube visto appunto quando detto che se disattivo KOD e vado ad usare KODI senza KOD stesso appunto il problema indicato scompare.
Però poi c'è la questione della SKIN così come la cosa della beta 3 ecc. ecc.

Nell'issue indicato ho anche allegato un kodi.log fatto col DEBUG LEVEL attivo:
https://github.com/user-attachments/files/15936304/kodidebuglog.txt

Se, a tempo perso ovviamente, potete darmi una vista al log e anche in base alle cose appena affermate sapere cosa può effettivamente creare il problema grazie in anticipo.

**Comment by xXTimmy89Xx** [comment]
Ho seguito la vicenda e a quanto pare la causa del problema era la versione 7.0.8 beta 4 dell'addon Youtube, pertanto chiudo.
