### ISSUE TITLE
Ilcorsaronero

### ISSUE THREAD

**Issue by Reneee69** [kodiondemand/addon#498]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Il corsaro nero il link non sembra essere disponibile

**Comment by xXTimmy89Xx** [comment]
> **Per poter scrivere o allegare file nella pagina devi:** - cliccare sui [ ... ] in alto a destra della scheda - Edit. Da questo momento puoi scrivere e/o inviare file.
> 
> Il corsaro nero il link non sembra essere disponibile

Il sito ormai negli ultimi mesi alterna dall'essere raggiungibile al non esserlo purtroppo, è per questo che è stato aggiunto i canale 1337x come alternativa
