### ISSUE TITLE
Aggiungere sito LordChannel

### ISSUE THREAD

**Issue by Rufusnightly** [kodiondemand/addon#502]
Salve potete aggiungere un nuovo sito?
https://lordchannel.com/

Grazie

**Comment by xXTimmy89Xx** [comment]
> Salve potete aggiungere un nuovo sito? https://lordchannel.com/
> 
> Grazie

Sito/canale attualmente disponibile nella versione Beta di KoD, verrà passato sulla versione stabile appena verrà ultimato.
