### ISSUE TITLE
Il corsaro nero

### ISSUE THREAD

**Issue by Alfonzo404** [kodiondemand/addon#503]
Salve a me da il messagio che il sito Il Corsaro Nero non funziona. Ma se andavo sul sito con un browser esiste.

**Comment by xXTimmy89Xx** [comment]
> Salve a me da il messagio che il sito Il Corsaro Nero non funziona. Ma se andavo sul sito con un browser esiste.

Ciao @Alfonzo404, attualmente il sito https://ilcorsaronero.link/ è irraggiungibile di conseguenza lo è il relativo canale su KoD, non resta che attendere che il sito torni a funzionare correttamente, intanto ti consiglio di usare il canale 1337x.
