### ISSUE TITLE
Problemi con TMDB TV Shows

### ISSUE THREAD

**Issue by Stormy-byte** [kodiondemand/addon#508]
In pratica quando aggiungo una serie TV e uso come database per i metadati The Movie Database mi da sempre errore, per il momento sono passato a TVDB, ma mi piacerebbe che risolvere (anche se penso sia un problema di Kodi)

**Comment by xXTimmy89Xx** [comment]
Ciao @Stormy-byte corretto, gli scrapers che si occupano di recuperare le informazioni per la libreria di Kodi non hanno nulla a che fare con KoD in quanto KoD ha i suoi scrapers interni, l'unica cosa che posso consigliarti di fare è verificare che tu abbia settato correttamente gli scrapers, con le ultime versioni di Kodi gli scrapers predefiniti sono
Per i FIlm: The Movie Database Python
Per le Serie TV: TMDb TV Shows
I vecchi scrapers The Movie Database sono stati contrassegnati come deprecati e non più funzionanti.
