### ISSUE TITLE
StreamingCommunity

### ISSUE THREAD

**Issue by DakoSoul94** [kodiondemand/addon#511]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Streamingcommunity.

- Indica il tipo di problema riscontrato, sii il più esauriente possibile. Che azione ha portato all'errore (Es. non riesco ad aggiungere film nella videoteca, ne dal menu contestuale, ne dalla voce in fondo alla lista dei server)
Dopo l ultimo aggiornamento dei domini, ho riscontrato problemi con streamingcommunity. Facendo "apri con il browser" ho notato che non aveva cambiato il dominio. Ho modificato il film xml aggiornando solo streamingcommunity, ma non è cambiato niente e continuo a non poter vedere niente con streamingcommunity. Avevo Streamingcommunity.computer e l ho aggiornato a streamingcommunity.asia. parlando con alcuni utenti nel gruppo telegram, in molti avevano riscontrato questo problema.

- Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20 e invialo qui.
Https://file.io/Q5vpjkBTTH2D

![Screenshot_20241206_050030_Kodi](https://github.com/user-attachments/assets/d6893ea6-0c0d-4599-a839-b3509687ee43)

**Comment by xXTimmy89Xx** [comment]
Ciao @DakoSoul94 , oltre al file log già fornito sarebbero utili ulteriori dettagli sul tuo operatore e sui DNS.

**Comment by DakoSoul94** [comment]
Fastweb e i dns sono di cloudfare

**Comment by xXTimmy89Xx** [comment]
> Fastweb e i dns sono di cloudfare

Cerca di fornire più dettagli, Fastweb mobile o fisso?  in caso di linea fissa che modem router stai utilizzando? Fastgate, Nexxt (con Alexa) o Nexxt One? sempre se non ti sei avvalso della delibera modem router libero, i DNS sono stati impostati nel dispositivo? stai usando una VPN? dai log risulta un IP "strano" ed è difficile stabilirne la causa in assenza di dettagli in più si vede che le richieste di connessione vs determinati siti vengono negate con errore 403.

**Comment by EspWifi8266** [comment]
Anche a me il canale streaming community non funziona non trova nessun film né serie, io uso un Tim hub e sono connesso ad una VPN, potrebbe essere un problema di dominio? Nel caso come faccio a vedere il dominio che sta utilizzando?

**Comment by EspWifi8266** [comment]
Io avevo lo stesso problema ma era legato alla VPN, ho provato a cercare sul canale streaming community senza VPN ed ha funzionato, non so se può essere di aiuto questa cosa

**Comment by xXTimmy89Xx** [comment]
> Io avevo lo stesso problema ma era legato alla VPN, ho provato a cercare sul canale streaming community senza VPN ed ha funzionato, non so se può essere di aiuto questa cosa

Corretto, come affrontato numerose volte, utilizzare una VPN con KoD è controproducente, in quanto i siti dalla quale KoD attinge i contenuti tendono a bannare/blacklistare gli IP delle VPN, siete liberissimi di provare a usarla ma in caso di malfunzionamento prima di segnalare eventuali problemi provate a spegnerla e verificate se il problema .

**Comment by Riello76** [comment]
Ciao io vivo a Londra, e ho lo stesso problema, premetto che funzionava fino a qualche giorno fa, io ho come link questo:  https://streamingcommunity.family/ che sul browser funziona.Una curiosita', il fatto che mi funzionino solo 3 o 4 canali dipende dal mio ip inglese?

**Comment by xXTimmy89Xx** [comment]
> Ciao io vivo a Londra, e ho lo stesso problema, premetto che funzionava fino a qualche giorno fa, io ho come link questo: https://streamingcommunity.family/ che sul browser funziona.Una curiosita', il fatto che mi funzionino solo 3 o 4 canali dipende dal mio ip inglese?

Ciao @Riello76, nel tuo caso l'utilizzo di una VPN che ti dia la possibilità di selezionare un Server/IP che ti geolocalizzi in Italia potrebbe aiutarti per il corretto funzionamento di alcuni siti/canali o almeno fino a quando l'indirizzo IP del serve Italiano della VPN non viene bannato/blacklistato, ovviamente nel caso tu non lo abbia già fatto imposta i DNS di Google o CloudFlare direttamente nelle impostazioni del modem router e nel caso non sia possibile causa limitazioni firmware impostali direttamente nelle impostazioni di rete del dispositivo.

**Comment by Riello76** [comment]
Mi> > Ciao io vivo a Londra, e ho lo stesso problema, premetto che funzionava fino a qualche giorno fa, io ho come link questo: https://streamingcommunity.family/ che sul browser funziona.Una curiosita', il fatto che mi funzionino solo 3 o 4 canali dipende dal mio ip inglese?
> 
> Ciao@Riello76, nel tuo caso l'utilizzo di una VPN che ti dia la possibilità di selezionare un Server/IP che ti geolocalizzi in Italia potrebbe aiutarti per il corretto funzionamento di alcuni siti/canali o almeno fino a quando l'indirizzo IP del serve Italiano della VPN non viene bannato/blacklistato, ovviamente nel caso tu non lo abbia già fatto imposta i DNS di Google o CloudFlare direttamente nelle impostazioni del modem router e nel caso non sia possibile causa limitazioni firmware impostali direttamente nelle impostazioni di rete del dispositivo.

Ciao  @xXTimmy89Xx  e grazie per la risposta,non credo che userò vpn,ho sostituito i DNS con quelli di CloudFlare nella speranza di un miglioramento,ma non è successo niente,aspetterò che prima o poi con i vari aggiornamenti dei domini,tornerà tutto ok.
