### ISSUE TITLE
Animeunity

### ISSUE THREAD

**Issue by iceblackmad** [kodiondemand/addon#512]
**Per poter scrivere o allegare file nella pagina devi:**
    - cliccare sui [ ... ] in alto a destra della scheda 
    - Edit. Da questo momento puoi scrivere e/o inviare file.

Inserisci il nome del canale Animeunity 

Problema indirizzo o struttura del sito

**Comment by xXTimmy89Xx** [comment]
E' stato appena rilasciato il fix, grazie della segnalazione
